/*
 * Amber API Server
 * Boon Logic Amber API server
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.boonamber.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.boonamber.client.model.EndpointUsage;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.boonamber.client.JSON;

/**
 * GetUsageResponseEndpoints
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class GetUsageResponseEndpoints {
  public static final String SERIALIZED_NAME_GET_MODEL = "getModel";
  @SerializedName(SERIALIZED_NAME_GET_MODEL)
  private EndpointUsage getModel;

  public static final String SERIALIZED_NAME_PUT_MODEL = "putModel";
  @SerializedName(SERIALIZED_NAME_PUT_MODEL)
  private EndpointUsage putModel;

  public static final String SERIALIZED_NAME_POST_CONFIG = "postConfig";
  @SerializedName(SERIALIZED_NAME_POST_CONFIG)
  private EndpointUsage postConfig;

  public static final String SERIALIZED_NAME_POST_LEARNING = "postLearning";
  @SerializedName(SERIALIZED_NAME_POST_LEARNING)
  private EndpointUsage postLearning;

  public static final String SERIALIZED_NAME_GET_CONFIG = "getConfig";
  @SerializedName(SERIALIZED_NAME_GET_CONFIG)
  private EndpointUsage getConfig;

  public static final String SERIALIZED_NAME_POST_DATA = "postData";
  @SerializedName(SERIALIZED_NAME_POST_DATA)
  private EndpointUsage postData;

  public static final String SERIALIZED_NAME_PUT_DATA = "putData";
  @SerializedName(SERIALIZED_NAME_PUT_DATA)
  private EndpointUsage putData;

  public static final String SERIALIZED_NAME_GET_STATUS = "getStatus";
  @SerializedName(SERIALIZED_NAME_GET_STATUS)
  private EndpointUsage getStatus;

  public static final String SERIALIZED_NAME_POST_PRETRAIN = "postPretrain";
  @SerializedName(SERIALIZED_NAME_POST_PRETRAIN)
  private EndpointUsage postPretrain;

  public static final String SERIALIZED_NAME_GET_PRETRAIN = "getPretrain";
  @SerializedName(SERIALIZED_NAME_GET_PRETRAIN)
  private EndpointUsage getPretrain;

  public static final String SERIALIZED_NAME_GET_ROOT_CAUSE = "getRootCause";
  @SerializedName(SERIALIZED_NAME_GET_ROOT_CAUSE)
  private EndpointUsage getRootCause;

  public static final String SERIALIZED_NAME_GET_USAGE = "getUsage";
  @SerializedName(SERIALIZED_NAME_GET_USAGE)
  private EndpointUsage getUsage;

  public static final String SERIALIZED_NAME_POST_OUTAGE = "postOutage";
  @SerializedName(SERIALIZED_NAME_POST_OUTAGE)
  private EndpointUsage postOutage;

  public GetUsageResponseEndpoints() {
  }

  public GetUsageResponseEndpoints getModel(EndpointUsage getModel) {
    
    this.getModel = getModel;
    return this;
  }

   /**
   * Get getModel
   * @return getModel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public EndpointUsage getGetModel() {
    return getModel;
  }


  public void setGetModel(EndpointUsage getModel) {
    this.getModel = getModel;
  }


  public GetUsageResponseEndpoints putModel(EndpointUsage putModel) {
    
    this.putModel = putModel;
    return this;
  }

   /**
   * Get putModel
   * @return putModel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public EndpointUsage getPutModel() {
    return putModel;
  }


  public void setPutModel(EndpointUsage putModel) {
    this.putModel = putModel;
  }


  public GetUsageResponseEndpoints postConfig(EndpointUsage postConfig) {
    
    this.postConfig = postConfig;
    return this;
  }

   /**
   * Get postConfig
   * @return postConfig
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public EndpointUsage getPostConfig() {
    return postConfig;
  }


  public void setPostConfig(EndpointUsage postConfig) {
    this.postConfig = postConfig;
  }


  public GetUsageResponseEndpoints postLearning(EndpointUsage postLearning) {
    
    this.postLearning = postLearning;
    return this;
  }

   /**
   * Get postLearning
   * @return postLearning
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public EndpointUsage getPostLearning() {
    return postLearning;
  }


  public void setPostLearning(EndpointUsage postLearning) {
    this.postLearning = postLearning;
  }


  public GetUsageResponseEndpoints getConfig(EndpointUsage getConfig) {
    
    this.getConfig = getConfig;
    return this;
  }

   /**
   * Get getConfig
   * @return getConfig
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public EndpointUsage getGetConfig() {
    return getConfig;
  }


  public void setGetConfig(EndpointUsage getConfig) {
    this.getConfig = getConfig;
  }


  public GetUsageResponseEndpoints postData(EndpointUsage postData) {
    
    this.postData = postData;
    return this;
  }

   /**
   * Get postData
   * @return postData
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public EndpointUsage getPostData() {
    return postData;
  }


  public void setPostData(EndpointUsage postData) {
    this.postData = postData;
  }


  public GetUsageResponseEndpoints putData(EndpointUsage putData) {
    
    this.putData = putData;
    return this;
  }

   /**
   * Get putData
   * @return putData
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public EndpointUsage getPutData() {
    return putData;
  }


  public void setPutData(EndpointUsage putData) {
    this.putData = putData;
  }


  public GetUsageResponseEndpoints getStatus(EndpointUsage getStatus) {
    
    this.getStatus = getStatus;
    return this;
  }

   /**
   * Get getStatus
   * @return getStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public EndpointUsage getGetStatus() {
    return getStatus;
  }


  public void setGetStatus(EndpointUsage getStatus) {
    this.getStatus = getStatus;
  }


  public GetUsageResponseEndpoints postPretrain(EndpointUsage postPretrain) {
    
    this.postPretrain = postPretrain;
    return this;
  }

   /**
   * Get postPretrain
   * @return postPretrain
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public EndpointUsage getPostPretrain() {
    return postPretrain;
  }


  public void setPostPretrain(EndpointUsage postPretrain) {
    this.postPretrain = postPretrain;
  }


  public GetUsageResponseEndpoints getPretrain(EndpointUsage getPretrain) {
    
    this.getPretrain = getPretrain;
    return this;
  }

   /**
   * Get getPretrain
   * @return getPretrain
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public EndpointUsage getGetPretrain() {
    return getPretrain;
  }


  public void setGetPretrain(EndpointUsage getPretrain) {
    this.getPretrain = getPretrain;
  }


  public GetUsageResponseEndpoints getRootCause(EndpointUsage getRootCause) {
    
    this.getRootCause = getRootCause;
    return this;
  }

   /**
   * Get getRootCause
   * @return getRootCause
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public EndpointUsage getGetRootCause() {
    return getRootCause;
  }


  public void setGetRootCause(EndpointUsage getRootCause) {
    this.getRootCause = getRootCause;
  }


  public GetUsageResponseEndpoints getUsage(EndpointUsage getUsage) {
    
    this.getUsage = getUsage;
    return this;
  }

   /**
   * Get getUsage
   * @return getUsage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public EndpointUsage getGetUsage() {
    return getUsage;
  }


  public void setGetUsage(EndpointUsage getUsage) {
    this.getUsage = getUsage;
  }


  public GetUsageResponseEndpoints postOutage(EndpointUsage postOutage) {
    
    this.postOutage = postOutage;
    return this;
  }

   /**
   * Get postOutage
   * @return postOutage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public EndpointUsage getPostOutage() {
    return postOutage;
  }


  public void setPostOutage(EndpointUsage postOutage) {
    this.postOutage = postOutage;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetUsageResponseEndpoints getUsageResponseEndpoints = (GetUsageResponseEndpoints) o;
    return Objects.equals(this.getModel, getUsageResponseEndpoints.getModel) &&
        Objects.equals(this.putModel, getUsageResponseEndpoints.putModel) &&
        Objects.equals(this.postConfig, getUsageResponseEndpoints.postConfig) &&
        Objects.equals(this.postLearning, getUsageResponseEndpoints.postLearning) &&
        Objects.equals(this.getConfig, getUsageResponseEndpoints.getConfig) &&
        Objects.equals(this.postData, getUsageResponseEndpoints.postData) &&
        Objects.equals(this.putData, getUsageResponseEndpoints.putData) &&
        Objects.equals(this.getStatus, getUsageResponseEndpoints.getStatus) &&
        Objects.equals(this.postPretrain, getUsageResponseEndpoints.postPretrain) &&
        Objects.equals(this.getPretrain, getUsageResponseEndpoints.getPretrain) &&
        Objects.equals(this.getRootCause, getUsageResponseEndpoints.getRootCause) &&
        Objects.equals(this.getUsage, getUsageResponseEndpoints.getUsage) &&
        Objects.equals(this.postOutage, getUsageResponseEndpoints.postOutage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(getModel, putModel, postConfig, postLearning, getConfig, postData, putData, getStatus, postPretrain, getPretrain, getRootCause, getUsage, postOutage);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetUsageResponseEndpoints {\n");
    sb.append("    getModel: ").append(toIndentedString(getModel)).append("\n");
    sb.append("    putModel: ").append(toIndentedString(putModel)).append("\n");
    sb.append("    postConfig: ").append(toIndentedString(postConfig)).append("\n");
    sb.append("    postLearning: ").append(toIndentedString(postLearning)).append("\n");
    sb.append("    getConfig: ").append(toIndentedString(getConfig)).append("\n");
    sb.append("    postData: ").append(toIndentedString(postData)).append("\n");
    sb.append("    putData: ").append(toIndentedString(putData)).append("\n");
    sb.append("    getStatus: ").append(toIndentedString(getStatus)).append("\n");
    sb.append("    postPretrain: ").append(toIndentedString(postPretrain)).append("\n");
    sb.append("    getPretrain: ").append(toIndentedString(getPretrain)).append("\n");
    sb.append("    getRootCause: ").append(toIndentedString(getRootCause)).append("\n");
    sb.append("    getUsage: ").append(toIndentedString(getUsage)).append("\n");
    sb.append("    postOutage: ").append(toIndentedString(postOutage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("getModel");
    openapiFields.add("putModel");
    openapiFields.add("postConfig");
    openapiFields.add("postLearning");
    openapiFields.add("getConfig");
    openapiFields.add("postData");
    openapiFields.add("putData");
    openapiFields.add("getStatus");
    openapiFields.add("postPretrain");
    openapiFields.add("getPretrain");
    openapiFields.add("getRootCause");
    openapiFields.add("getUsage");
    openapiFields.add("postOutage");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to GetUsageResponseEndpoints
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!GetUsageResponseEndpoints.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GetUsageResponseEndpoints is not found in the empty JSON string", GetUsageResponseEndpoints.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!GetUsageResponseEndpoints.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GetUsageResponseEndpoints` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      // validate the optional field `getModel`
      if (jsonObj.get("getModel") != null && !jsonObj.get("getModel").isJsonNull()) {
        EndpointUsage.validateJsonObject(jsonObj.getAsJsonObject("getModel"));
      }
      // validate the optional field `putModel`
      if (jsonObj.get("putModel") != null && !jsonObj.get("putModel").isJsonNull()) {
        EndpointUsage.validateJsonObject(jsonObj.getAsJsonObject("putModel"));
      }
      // validate the optional field `postConfig`
      if (jsonObj.get("postConfig") != null && !jsonObj.get("postConfig").isJsonNull()) {
        EndpointUsage.validateJsonObject(jsonObj.getAsJsonObject("postConfig"));
      }
      // validate the optional field `postLearning`
      if (jsonObj.get("postLearning") != null && !jsonObj.get("postLearning").isJsonNull()) {
        EndpointUsage.validateJsonObject(jsonObj.getAsJsonObject("postLearning"));
      }
      // validate the optional field `getConfig`
      if (jsonObj.get("getConfig") != null && !jsonObj.get("getConfig").isJsonNull()) {
        EndpointUsage.validateJsonObject(jsonObj.getAsJsonObject("getConfig"));
      }
      // validate the optional field `postData`
      if (jsonObj.get("postData") != null && !jsonObj.get("postData").isJsonNull()) {
        EndpointUsage.validateJsonObject(jsonObj.getAsJsonObject("postData"));
      }
      // validate the optional field `putData`
      if (jsonObj.get("putData") != null && !jsonObj.get("putData").isJsonNull()) {
        EndpointUsage.validateJsonObject(jsonObj.getAsJsonObject("putData"));
      }
      // validate the optional field `getStatus`
      if (jsonObj.get("getStatus") != null && !jsonObj.get("getStatus").isJsonNull()) {
        EndpointUsage.validateJsonObject(jsonObj.getAsJsonObject("getStatus"));
      }
      // validate the optional field `postPretrain`
      if (jsonObj.get("postPretrain") != null && !jsonObj.get("postPretrain").isJsonNull()) {
        EndpointUsage.validateJsonObject(jsonObj.getAsJsonObject("postPretrain"));
      }
      // validate the optional field `getPretrain`
      if (jsonObj.get("getPretrain") != null && !jsonObj.get("getPretrain").isJsonNull()) {
        EndpointUsage.validateJsonObject(jsonObj.getAsJsonObject("getPretrain"));
      }
      // validate the optional field `getRootCause`
      if (jsonObj.get("getRootCause") != null && !jsonObj.get("getRootCause").isJsonNull()) {
        EndpointUsage.validateJsonObject(jsonObj.getAsJsonObject("getRootCause"));
      }
      // validate the optional field `getUsage`
      if (jsonObj.get("getUsage") != null && !jsonObj.get("getUsage").isJsonNull()) {
        EndpointUsage.validateJsonObject(jsonObj.getAsJsonObject("getUsage"));
      }
      // validate the optional field `postOutage`
      if (jsonObj.get("postOutage") != null && !jsonObj.get("postOutage").isJsonNull()) {
        EndpointUsage.validateJsonObject(jsonObj.getAsJsonObject("postOutage"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetUsageResponseEndpoints.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetUsageResponseEndpoints' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetUsageResponseEndpoints> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetUsageResponseEndpoints.class));

       return (TypeAdapter<T>) new TypeAdapter<GetUsageResponseEndpoints>() {
           @Override
           public void write(JsonWriter out, GetUsageResponseEndpoints value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetUsageResponseEndpoints read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of GetUsageResponseEndpoints given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of GetUsageResponseEndpoints
  * @throws IOException if the JSON string is invalid with respect to GetUsageResponseEndpoints
  */
  public static GetUsageResponseEndpoints fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetUsageResponseEndpoints.class);
  }

 /**
  * Convert an instance of GetUsageResponseEndpoints to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

