/*
 * Amber API Server
 * Boon Logic Amber API server
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.boonamber.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.boonamber.client.model.FeatureConfig;
import org.boonamber.client.model.TrainingConfig;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Config
 */
public class ConfigTest {
    private final Config model = new Config();

    /**
     * Model tests for Config
     */
    @Test
    public void testConfig() {
        // TODO: test Config
    }

    /**
     * Test the property 'streamingWindow'
     */
    @Test
    public void streamingWindowTest() {
        // TODO: test streamingWindow
    }

    /**
     * Test the property 'percentVariation'
     */
    @Test
    public void percentVariationTest() {
        // TODO: test percentVariation
    }

    /**
     * Test the property 'features'
     */
    @Test
    public void featuresTest() {
        // TODO: test features
    }

    /**
     * Test the property 'training'
     */
    @Test
    public void trainingTest() {
        // TODO: test training
    }

}
