/*
 * Amber API Server
 * Boon Logic Amber API server
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.boonamber.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TrainingConfig
 */
public class TrainingConfigTest {
    private final TrainingConfig model = new TrainingConfig();

    /**
     * Model tests for TrainingConfig
     */
    @Test
    public void testTrainingConfig() {
        // TODO: test TrainingConfig
    }

    /**
     * Test the property 'historyWindow'
     */
    @Test
    public void historyWindowTest() {
        // TODO: test historyWindow
    }

    /**
     * Test the property 'bufferingSamples'
     */
    @Test
    public void bufferingSamplesTest() {
        // TODO: test bufferingSamples
    }

    /**
     * Test the property 'learningMaxSamples'
     */
    @Test
    public void learningMaxSamplesTest() {
        // TODO: test learningMaxSamples
    }

    /**
     * Test the property 'learningMaxClusters'
     */
    @Test
    public void learningMaxClustersTest() {
        // TODO: test learningMaxClusters
    }

    /**
     * Test the property 'learningRateNumerator'
     */
    @Test
    public void learningRateNumeratorTest() {
        // TODO: test learningRateNumerator
    }

    /**
     * Test the property 'learningRateDenominator'
     */
    @Test
    public void learningRateDenominatorTest() {
        // TODO: test learningRateDenominator
    }

}
