apiPackage: "org.boonamber.client.api"
hideGenerationTimestamp: true
invokerPackage: "org.boonamber.client"
modelPackage: "org.boonamber.client.model"
artifactId: "boonamber"
artifactVersion: "2.0.0"
artifactDescription: "Amber Java SDK"