/*
 * Amber API Server
 * Boon Logic Amber API server
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.FusionFeature;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for GetDataResponse
 */
public class GetDataResponseTest {
    private final GetDataResponse model = new GetDataResponse();

    /**
     * Model tests for GetDataResponse
     */
    @Test
    public void testGetDataResponse() {
        // TODO: test GetDataResponse
    }

    /**
     * Test the property 'vector'
     */
    @Test
    public void vectorTest() {
        // TODO: test vector
    }

}
