/*
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.SensorUsageInfo;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for GetSensorResponse
 */
public class GetSensorResponseTest {
    private final GetSensorResponse model = new GetSensorResponse();

    /**
     * Model tests for GetSensorResponse
     */
    @Test
    public void testGetSensorResponse() {
        // TODO: test GetSensorResponse
    }

    /**
     * Test the property 'label'
     */
    @Test
    public void labelTest() {
        // TODO: test label
    }

    /**
     * Test the property 'sensorId'
     */
    @Test
    public void sensorIdTest() {
        // TODO: test sensorId
    }

    /**
     * Test the property 'usageInfo'
     */
    @Test
    public void usageInfoTest() {
        // TODO: test usageInfo
    }

}
