/*
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.MPatternMemory;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for MNanoBackend
 */
public class MNanoBackendTest {
    private final MNanoBackend model = new MNanoBackend();

    /**
     * Model tests for MNanoBackend
     */
    @Test
    public void testMNanoBackend() {
        // TODO: test MNanoBackend
    }

    /**
     * Test the property 'versionNumber'
     */
    @Test
    public void versionNumberTest() {
        // TODO: test versionNumber
    }

    /**
     * Test the property 'mPatternMemory'
     */
    @Test
    public void mPatternMemoryTest() {
        // TODO: test mPatternMemory
    }

    /**
     * Test the property 'mInitComplete'
     */
    @Test
    public void mInitCompleteTest() {
        // TODO: test mInitComplete
    }

    /**
     * Test the property 'mPatternLength'
     */
    @Test
    public void mPatternLengthTest() {
        // TODO: test mPatternLength
    }

    /**
     * Test the property 'mLearningIsOn'
     */
    @Test
    public void mLearningIsOnTest() {
        // TODO: test mLearningIsOn
    }

    /**
     * Test the property 'mNumOfPatternsClustered'
     */
    @Test
    public void mNumOfPatternsClusteredTest() {
        // TODO: test mNumOfPatternsClustered
    }

}
