/*
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for MNCP
 */
public class MNCPTest {
    private final MNCP model = new MNCP();

    /**
     * Model tests for MNCP
     */
    @Test
    public void testMNCP() {
        // TODO: test MNCP
    }

    /**
     * Test the property 'versionNumber'
     */
    @Test
    public void versionNumberTest() {
        // TODO: test versionNumber
    }

    /**
     * Test the property 'numOfFeatures'
     */
    @Test
    public void numOfFeaturesTest() {
        // TODO: test numOfFeatures
    }

    /**
     * Test the property 'mNumericFormat'
     */
    @Test
    public void mNumericFormatTest() {
        // TODO: test mNumericFormat
    }

    /**
     * Test the property 'mPercentVariation'
     */
    @Test
    public void mPercentVariationTest() {
        // TODO: test mPercentVariation
    }

    /**
     * Test the property 'mAccuracy'
     */
    @Test
    public void mAccuracyTest() {
        // TODO: test mAccuracy
    }

    /**
     * Test the property 'mStreamingWindowSize'
     */
    @Test
    public void mStreamingWindowSizeTest() {
        // TODO: test mStreamingWindowSize
    }

}
