/*
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for MStreamingParameters
 */
public class MStreamingParametersTest {
    private final MStreamingParameters model = new MStreamingParameters();

    /**
     * Model tests for MStreamingParameters
     */
    @Test
    public void testMStreamingParameters() {
        // TODO: test MStreamingParameters
    }

    /**
     * Test the property 'versionNumber'
     */
    @Test
    public void versionNumberTest() {
        // TODO: test versionNumber
    }

    /**
     * Test the property 'mEnableAutotuning'
     */
    @Test
    public void mEnableAutotuningTest() {
        // TODO: test mEnableAutotuning
    }

    /**
     * Test the property 'mSamplesToBufferForAutotuning'
     */
    @Test
    public void mSamplesToBufferForAutotuningTest() {
        // TODO: test mSamplesToBufferForAutotuning
    }

    /**
     * Test the property 'mGraduationAtRateNumerator'
     */
    @Test
    public void mGraduationAtRateNumeratorTest() {
        // TODO: test mGraduationAtRateNumerator
    }

    /**
     * Test the property 'mGraduationAtRateDenominator'
     */
    @Test
    public void mGraduationAtRateDenominatorTest() {
        // TODO: test mGraduationAtRateDenominator
    }

    /**
     * Test the property 'mGraduateAtMaxClusters'
     */
    @Test
    public void mGraduateAtMaxClustersTest() {
        // TODO: test mGraduateAtMaxClusters
    }

    /**
     * Test the property 'mGraduateAtMaxSamples'
     */
    @Test
    public void mGraduateAtMaxSamplesTest() {
        // TODO: test mGraduateAtMaxSamples
    }

}
