/*
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.FeatureConfig;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PostConfigResponse
 */
public class PostConfigResponseTest {
    private final PostConfigResponse model = new PostConfigResponse();

    /**
     * Model tests for PostConfigResponse
     */
    @Test
    public void testPostConfigResponse() {
        // TODO: test PostConfigResponse
    }

    /**
     * Test the property 'anomalyHistoryWindow'
     */
    @Test
    public void anomalyHistoryWindowTest() {
        // TODO: test anomalyHistoryWindow
    }

    /**
     * Test the property 'learningRateNumerator'
     */
    @Test
    public void learningRateNumeratorTest() {
        // TODO: test learningRateNumerator
    }

    /**
     * Test the property 'learningRateDenominator'
     */
    @Test
    public void learningRateDenominatorTest() {
        // TODO: test learningRateDenominator
    }

    /**
     * Test the property 'learningMaxClusters'
     */
    @Test
    public void learningMaxClustersTest() {
        // TODO: test learningMaxClusters
    }

    /**
     * Test the property 'learningMaxSamples'
     */
    @Test
    public void learningMaxSamplesTest() {
        // TODO: test learningMaxSamples
    }

    /**
     * Test the property 'featureCount'
     */
    @Test
    public void featureCountTest() {
        // TODO: test featureCount
    }

    /**
     * Test the property 'streamingWindowSize'
     */
    @Test
    public void streamingWindowSizeTest() {
        // TODO: test streamingWindowSize
    }

    /**
     * Test the property 'features'
     */
    @Test
    public void featuresTest() {
        // TODO: test features
    }

    /**
     * Test the property 'samplesToBuffer'
     */
    @Test
    public void samplesToBufferTest() {
        // TODO: test samplesToBuffer
    }

    /**
     * Test the property 'percentVariationOverride'
     */
    @Test
    public void percentVariationOverrideTest() {
        // TODO: test percentVariationOverride
    }

}
