/*
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for StreamingEndpointUsageInfo
 */
public class StreamingEndpointUsageInfoTest {
    private final StreamingEndpointUsageInfo model = new StreamingEndpointUsageInfo();

    /**
     * Model tests for StreamingEndpointUsageInfo
     */
    @Test
    public void testStreamingEndpointUsageInfo() {
        // TODO: test StreamingEndpointUsageInfo
    }

    /**
     * Test the property 'callsTotal'
     */
    @Test
    public void callsTotalTest() {
        // TODO: test callsTotal
    }

    /**
     * Test the property 'callsThisPeriod'
     */
    @Test
    public void callsThisPeriodTest() {
        // TODO: test callsThisPeriod
    }

    /**
     * Test the property 'samplesTotal'
     */
    @Test
    public void samplesTotalTest() {
        // TODO: test samplesTotal
    }

    /**
     * Test the property 'samplesThisPeriod'
     */
    @Test
    public void samplesThisPeriodTest() {
        // TODO: test samplesThisPeriod
    }

    /**
     * Test the property 'lastCalled'
     */
    @Test
    public void lastCalledTest() {
        // TODO: test lastCalled
    }

}
