/*
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * FusionConfig
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-10-20T15:52:03.807427-05:00[America/Chicago]")
public class FusionConfig {
  @SerializedName("label")
  private String label = null;

  /**
   * policy for submitting sensor fusion vector when this feature is updated. One of \&quot;submit\&quot;, \&quot;nosubmit\&quot; (defaults to \&quot;submit\&quot;)
   */
  @JsonAdapter(SubmitRuleEnum.Adapter.class)
  public enum SubmitRuleEnum {
    SUBMIT("submit"),
    NOSUBMIT("nosubmit");

    private String value;

    SubmitRuleEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static SubmitRuleEnum fromValue(String input) {
      for (SubmitRuleEnum b : SubmitRuleEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<SubmitRuleEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SubmitRuleEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public SubmitRuleEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return SubmitRuleEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("submitRule")
  private SubmitRuleEnum submitRule = null;

  public FusionConfig label(String label) {
    this.label = label;
    return this;
  }

   /**
   * label associated with feature
   * @return label
  **/
  @Schema(required = true, description = "label associated with feature")
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public FusionConfig submitRule(SubmitRuleEnum submitRule) {
    this.submitRule = submitRule;
    return this;
  }

   /**
   * policy for submitting sensor fusion vector when this feature is updated. One of \&quot;submit\&quot;, \&quot;nosubmit\&quot; (defaults to \&quot;submit\&quot;)
   * @return submitRule
  **/
  @Schema(description = "policy for submitting sensor fusion vector when this feature is updated. One of \"submit\", \"nosubmit\" (defaults to \"submit\")")
  public SubmitRuleEnum getSubmitRule() {
    return submitRule;
  }

  public void setSubmitRule(SubmitRuleEnum submitRule) {
    this.submitRule = submitRule;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FusionConfig fusionConfig = (FusionConfig) o;
    return Objects.equals(this.label, fusionConfig.label) &&
        Objects.equals(this.submitRule, fusionConfig.submitRule);
  }

  @Override
  public int hashCode() {
    return Objects.hash(label, submitRule);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FusionConfig {\n");
    
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    submitRule: ").append(toIndentedString(submitRule)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
