/*
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * MAP
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-10-20T15:52:03.807427-05:00[America/Chicago]")
public class MAP {
  @SerializedName("VersionNumber")
  private Integer versionNumber = null;

  @SerializedName("m_AutotuneRange")
  private Boolean mAutotuneRange = null;

  @SerializedName("m_AutotunePV")
  private Boolean mAutotunePV = null;

  @SerializedName("m_AutotuneByFeatures")
  private Boolean mAutotuneByFeatures = null;

  @SerializedName("m_MaxClusters")
  private Integer mMaxClusters = null;

  @SerializedName("m_FeaturesToTuneArray")
  private List<Integer> mFeaturesToTuneArray = null;

  public MAP versionNumber(Integer versionNumber) {
    this.versionNumber = versionNumber;
    return this;
  }

   /**
   * Get versionNumber
   * @return versionNumber
  **/
  @Schema(description = "")
  public Integer getVersionNumber() {
    return versionNumber;
  }

  public void setVersionNumber(Integer versionNumber) {
    this.versionNumber = versionNumber;
  }

  public MAP mAutotuneRange(Boolean mAutotuneRange) {
    this.mAutotuneRange = mAutotuneRange;
    return this;
  }

   /**
   * Get mAutotuneRange
   * @return mAutotuneRange
  **/
  @Schema(required = true, description = "")
  public Boolean isMAutotuneRange() {
    return mAutotuneRange;
  }

  public void setMAutotuneRange(Boolean mAutotuneRange) {
    this.mAutotuneRange = mAutotuneRange;
  }

  public MAP mAutotunePV(Boolean mAutotunePV) {
    this.mAutotunePV = mAutotunePV;
    return this;
  }

   /**
   * Get mAutotunePV
   * @return mAutotunePV
  **/
  @Schema(required = true, description = "")
  public Boolean isMAutotunePV() {
    return mAutotunePV;
  }

  public void setMAutotunePV(Boolean mAutotunePV) {
    this.mAutotunePV = mAutotunePV;
  }

  public MAP mAutotuneByFeatures(Boolean mAutotuneByFeatures) {
    this.mAutotuneByFeatures = mAutotuneByFeatures;
    return this;
  }

   /**
   * Get mAutotuneByFeatures
   * @return mAutotuneByFeatures
  **/
  @Schema(required = true, description = "")
  public Boolean isMAutotuneByFeatures() {
    return mAutotuneByFeatures;
  }

  public void setMAutotuneByFeatures(Boolean mAutotuneByFeatures) {
    this.mAutotuneByFeatures = mAutotuneByFeatures;
  }

  public MAP mMaxClusters(Integer mMaxClusters) {
    this.mMaxClusters = mMaxClusters;
    return this;
  }

   /**
   * Get mMaxClusters
   * @return mMaxClusters
  **/
  @Schema(description = "")
  public Integer getMMaxClusters() {
    return mMaxClusters;
  }

  public void setMMaxClusters(Integer mMaxClusters) {
    this.mMaxClusters = mMaxClusters;
  }

  public MAP mFeaturesToTuneArray(List<Integer> mFeaturesToTuneArray) {
    this.mFeaturesToTuneArray = mFeaturesToTuneArray;
    return this;
  }

  public MAP addMFeaturesToTuneArrayItem(Integer mFeaturesToTuneArrayItem) {
    if (this.mFeaturesToTuneArray == null) {
      this.mFeaturesToTuneArray = new ArrayList<Integer>();
    }
    this.mFeaturesToTuneArray.add(mFeaturesToTuneArrayItem);
    return this;
  }

   /**
   * Get mFeaturesToTuneArray
   * @return mFeaturesToTuneArray
  **/
  @Schema(description = "")
  public List<Integer> getMFeaturesToTuneArray() {
    return mFeaturesToTuneArray;
  }

  public void setMFeaturesToTuneArray(List<Integer> mFeaturesToTuneArray) {
    this.mFeaturesToTuneArray = mFeaturesToTuneArray;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MAP mAP = (MAP) o;
    return Objects.equals(this.versionNumber, mAP.versionNumber) &&
        Objects.equals(this.mAutotuneRange, mAP.mAutotuneRange) &&
        Objects.equals(this.mAutotunePV, mAP.mAutotunePV) &&
        Objects.equals(this.mAutotuneByFeatures, mAP.mAutotuneByFeatures) &&
        Objects.equals(this.mMaxClusters, mAP.mMaxClusters) &&
        Objects.equals(this.mFeaturesToTuneArray, mAP.mFeaturesToTuneArray);
  }

  @Override
  public int hashCode() {
    return Objects.hash(versionNumber, mAutotuneRange, mAutotunePV, mAutotuneByFeatures, mMaxClusters, mFeaturesToTuneArray);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MAP {\n");
    
    sb.append("    versionNumber: ").append(toIndentedString(versionNumber)).append("\n");
    sb.append("    mAutotuneRange: ").append(toIndentedString(mAutotuneRange)).append("\n");
    sb.append("    mAutotunePV: ").append(toIndentedString(mAutotunePV)).append("\n");
    sb.append("    mAutotuneByFeatures: ").append(toIndentedString(mAutotuneByFeatures)).append("\n");
    sb.append("    mMaxClusters: ").append(toIndentedString(mMaxClusters)).append("\n");
    sb.append("    mFeaturesToTuneArray: ").append(toIndentedString(mFeaturesToTuneArray)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
