/*
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Float32Array;
import io.swagger.client.model.Int32Array;
import io.swagger.client.model.StreamStatus;
import io.swagger.client.model.Uint16Array;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
/**
 * PostStreamResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-10-20T15:52:03.807427-05:00[America/Chicago]")
public class PostStreamResponse extends StreamStatus {
  @SerializedName("RI")
  private Uint16Array RI = null;

  @SerializedName("SI")
  private Uint16Array SI = null;

  @SerializedName("AD")
  private Uint16Array AD = null;

  @SerializedName("AH")
  private Uint16Array AH = null;

  @SerializedName("AM")
  private Float32Array AM = null;

  @SerializedName("AW")
  private Uint16Array AW = null;

  @SerializedName("ID")
  private Int32Array ID = null;

  public PostStreamResponse RI(Uint16Array RI) {
    this.RI = RI;
    return this;
  }

   /**
   * Get RI
   * @return RI
  **/
  @Schema(required = true, description = "")
  public Uint16Array getRI() {
    return RI;
  }

  public void setRI(Uint16Array RI) {
    this.RI = RI;
  }

  public PostStreamResponse SI(Uint16Array SI) {
    this.SI = SI;
    return this;
  }

   /**
   * Get SI
   * @return SI
  **/
  @Schema(required = true, description = "")
  public Uint16Array getSI() {
    return SI;
  }

  public void setSI(Uint16Array SI) {
    this.SI = SI;
  }

  public PostStreamResponse AD(Uint16Array AD) {
    this.AD = AD;
    return this;
  }

   /**
   * Get AD
   * @return AD
  **/
  @Schema(required = true, description = "")
  public Uint16Array getAD() {
    return AD;
  }

  public void setAD(Uint16Array AD) {
    this.AD = AD;
  }

  public PostStreamResponse AH(Uint16Array AH) {
    this.AH = AH;
    return this;
  }

   /**
   * Get AH
   * @return AH
  **/
  @Schema(required = true, description = "")
  public Uint16Array getAH() {
    return AH;
  }

  public void setAH(Uint16Array AH) {
    this.AH = AH;
  }

  public PostStreamResponse AM(Float32Array AM) {
    this.AM = AM;
    return this;
  }

   /**
   * Get AM
   * @return AM
  **/
  @Schema(required = true, description = "")
  public Float32Array getAM() {
    return AM;
  }

  public void setAM(Float32Array AM) {
    this.AM = AM;
  }

  public PostStreamResponse AW(Uint16Array AW) {
    this.AW = AW;
    return this;
  }

   /**
   * Get AW
   * @return AW
  **/
  @Schema(required = true, description = "")
  public Uint16Array getAW() {
    return AW;
  }

  public void setAW(Uint16Array AW) {
    this.AW = AW;
  }

  public PostStreamResponse ID(Int32Array ID) {
    this.ID = ID;
    return this;
  }

   /**
   * Get ID
   * @return ID
  **/
  @Schema(required = true, description = "")
  public Int32Array getID() {
    return ID;
  }

  public void setID(Int32Array ID) {
    this.ID = ID;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostStreamResponse postStreamResponse = (PostStreamResponse) o;
    return Objects.equals(this.RI, postStreamResponse.RI) &&
        Objects.equals(this.SI, postStreamResponse.SI) &&
        Objects.equals(this.AD, postStreamResponse.AD) &&
        Objects.equals(this.AH, postStreamResponse.AH) &&
        Objects.equals(this.AM, postStreamResponse.AM) &&
        Objects.equals(this.AW, postStreamResponse.AW) &&
        Objects.equals(this.ID, postStreamResponse.ID) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(RI, SI, AD, AH, AM, AW, ID, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostStreamResponse {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    RI: ").append(toIndentedString(RI)).append("\n");
    sb.append("    SI: ").append(toIndentedString(SI)).append("\n");
    sb.append("    AD: ").append(toIndentedString(AD)).append("\n");
    sb.append("    AH: ").append(toIndentedString(AH)).append("\n");
    sb.append("    AM: ").append(toIndentedString(AM)).append("\n");
    sb.append("    AW: ").append(toIndentedString(AW)).append("\n");
    sb.append("    ID: ").append(toIndentedString(ID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
