/*
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.FusionConfig;
import io.swagger.client.model.LearningParameters;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * PutConfigRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-10-20T15:52:03.807427-05:00[America/Chicago]")
public class PutConfigRequest {
  @SerializedName("features")
  private List<FusionConfig> features = null;

  @SerializedName("streaming")
  private LearningParameters streaming = null;

  public PutConfigRequest features(List<FusionConfig> features) {
    this.features = features;
    return this;
  }

  public PutConfigRequest addFeaturesItem(FusionConfig featuresItem) {
    if (this.features == null) {
      this.features = new ArrayList<FusionConfig>();
    }
    this.features.add(featuresItem);
    return this;
  }

   /**
   * Get features
   * @return features
  **/
  @Schema(description = "")
  public List<FusionConfig> getFeatures() {
    return features;
  }

  public void setFeatures(List<FusionConfig> features) {
    this.features = features;
  }

  public PutConfigRequest streaming(LearningParameters streaming) {
    this.streaming = streaming;
    return this;
  }

   /**
   * Get streaming
   * @return streaming
  **/
  @Schema(description = "")
  public LearningParameters getStreaming() {
    return streaming;
  }

  public void setStreaming(LearningParameters streaming) {
    this.streaming = streaming;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PutConfigRequest putConfigRequest = (PutConfigRequest) o;
    return Objects.equals(this.features, putConfigRequest.features) &&
        Objects.equals(this.streaming, putConfigRequest.streaming);
  }

  @Override
  public int hashCode() {
    return Objects.hash(features, streaming);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PutConfigRequest {\n");
    
    sb.append("    features: ").append(toIndentedString(features)).append("\n");
    sb.append("    streaming: ").append(toIndentedString(streaming)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
