/*
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.EndpointUsageInfo;
import io.swagger.client.model.StreamingEndpointUsageInfo;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * SensorUsageInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-10-20T15:52:03.807427-05:00[America/Chicago]")
public class SensorUsageInfo {
  @SerializedName("postConfig")
  private EndpointUsageInfo postConfig = null;

  @SerializedName("postOutage")
  private EndpointUsageInfo postOutage = null;

  @SerializedName("postStream")
  private StreamingEndpointUsageInfo postStream = null;

  @SerializedName("putSensor")
  private EndpointUsageInfo putSensor = null;

  @SerializedName("getSensor")
  private EndpointUsageInfo getSensor = null;

  @SerializedName("getConfig")
  private EndpointUsageInfo getConfig = null;

  @SerializedName("getStatus")
  private EndpointUsageInfo getStatus = null;

  @SerializedName("getRootCause")
  private EndpointUsageInfo getRootCause = null;

  @SerializedName("getAmberSummary")
  private EndpointUsageInfo getAmberSummary = null;

  @SerializedName("postPretrain")
  private EndpointUsageInfo postPretrain = null;

  @SerializedName("getPretrain")
  private EndpointUsageInfo getPretrain = null;

  public SensorUsageInfo postConfig(EndpointUsageInfo postConfig) {
    this.postConfig = postConfig;
    return this;
  }

   /**
   * Get postConfig
   * @return postConfig
  **/
  @Schema(required = true, description = "")
  public EndpointUsageInfo getPostConfig() {
    return postConfig;
  }

  public void setPostConfig(EndpointUsageInfo postConfig) {
    this.postConfig = postConfig;
  }

  public SensorUsageInfo postOutage(EndpointUsageInfo postOutage) {
    this.postOutage = postOutage;
    return this;
  }

   /**
   * Get postOutage
   * @return postOutage
  **/
  @Schema(required = true, description = "")
  public EndpointUsageInfo getPostOutage() {
    return postOutage;
  }

  public void setPostOutage(EndpointUsageInfo postOutage) {
    this.postOutage = postOutage;
  }

  public SensorUsageInfo postStream(StreamingEndpointUsageInfo postStream) {
    this.postStream = postStream;
    return this;
  }

   /**
   * Get postStream
   * @return postStream
  **/
  @Schema(required = true, description = "")
  public StreamingEndpointUsageInfo getPostStream() {
    return postStream;
  }

  public void setPostStream(StreamingEndpointUsageInfo postStream) {
    this.postStream = postStream;
  }

  public SensorUsageInfo putSensor(EndpointUsageInfo putSensor) {
    this.putSensor = putSensor;
    return this;
  }

   /**
   * Get putSensor
   * @return putSensor
  **/
  @Schema(required = true, description = "")
  public EndpointUsageInfo getPutSensor() {
    return putSensor;
  }

  public void setPutSensor(EndpointUsageInfo putSensor) {
    this.putSensor = putSensor;
  }

  public SensorUsageInfo getSensor(EndpointUsageInfo getSensor) {
    this.getSensor = getSensor;
    return this;
  }

   /**
   * Get getSensor
   * @return getSensor
  **/
  @Schema(required = true, description = "")
  public EndpointUsageInfo getGetSensor() {
    return getSensor;
  }

  public void setGetSensor(EndpointUsageInfo getSensor) {
    this.getSensor = getSensor;
  }

  public SensorUsageInfo getConfig(EndpointUsageInfo getConfig) {
    this.getConfig = getConfig;
    return this;
  }

   /**
   * Get getConfig
   * @return getConfig
  **/
  @Schema(required = true, description = "")
  public EndpointUsageInfo getGetConfig() {
    return getConfig;
  }

  public void setGetConfig(EndpointUsageInfo getConfig) {
    this.getConfig = getConfig;
  }

  public SensorUsageInfo getStatus(EndpointUsageInfo getStatus) {
    this.getStatus = getStatus;
    return this;
  }

   /**
   * Get getStatus
   * @return getStatus
  **/
  @Schema(required = true, description = "")
  public EndpointUsageInfo getGetStatus() {
    return getStatus;
  }

  public void setGetStatus(EndpointUsageInfo getStatus) {
    this.getStatus = getStatus;
  }

  public SensorUsageInfo getRootCause(EndpointUsageInfo getRootCause) {
    this.getRootCause = getRootCause;
    return this;
  }

   /**
   * Get getRootCause
   * @return getRootCause
  **/
  @Schema(required = true, description = "")
  public EndpointUsageInfo getGetRootCause() {
    return getRootCause;
  }

  public void setGetRootCause(EndpointUsageInfo getRootCause) {
    this.getRootCause = getRootCause;
  }

  public SensorUsageInfo getAmberSummary(EndpointUsageInfo getAmberSummary) {
    this.getAmberSummary = getAmberSummary;
    return this;
  }

   /**
   * Get getAmberSummary
   * @return getAmberSummary
  **/
  @Schema(required = true, description = "")
  public EndpointUsageInfo getGetAmberSummary() {
    return getAmberSummary;
  }

  public void setGetAmberSummary(EndpointUsageInfo getAmberSummary) {
    this.getAmberSummary = getAmberSummary;
  }

  public SensorUsageInfo postPretrain(EndpointUsageInfo postPretrain) {
    this.postPretrain = postPretrain;
    return this;
  }

   /**
   * Get postPretrain
   * @return postPretrain
  **/
  @Schema(required = true, description = "")
  public EndpointUsageInfo getPostPretrain() {
    return postPretrain;
  }

  public void setPostPretrain(EndpointUsageInfo postPretrain) {
    this.postPretrain = postPretrain;
  }

  public SensorUsageInfo getPretrain(EndpointUsageInfo getPretrain) {
    this.getPretrain = getPretrain;
    return this;
  }

   /**
   * Get getPretrain
   * @return getPretrain
  **/
  @Schema(required = true, description = "")
  public EndpointUsageInfo getGetPretrain() {
    return getPretrain;
  }

  public void setGetPretrain(EndpointUsageInfo getPretrain) {
    this.getPretrain = getPretrain;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SensorUsageInfo sensorUsageInfo = (SensorUsageInfo) o;
    return Objects.equals(this.postConfig, sensorUsageInfo.postConfig) &&
        Objects.equals(this.postOutage, sensorUsageInfo.postOutage) &&
        Objects.equals(this.postStream, sensorUsageInfo.postStream) &&
        Objects.equals(this.putSensor, sensorUsageInfo.putSensor) &&
        Objects.equals(this.getSensor, sensorUsageInfo.getSensor) &&
        Objects.equals(this.getConfig, sensorUsageInfo.getConfig) &&
        Objects.equals(this.getStatus, sensorUsageInfo.getStatus) &&
        Objects.equals(this.getRootCause, sensorUsageInfo.getRootCause) &&
        Objects.equals(this.getAmberSummary, sensorUsageInfo.getAmberSummary) &&
        Objects.equals(this.postPretrain, sensorUsageInfo.postPretrain) &&
        Objects.equals(this.getPretrain, sensorUsageInfo.getPretrain);
  }

  @Override
  public int hashCode() {
    return Objects.hash(postConfig, postOutage, postStream, putSensor, getSensor, getConfig, getStatus, getRootCause, getAmberSummary, postPretrain, getPretrain);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SensorUsageInfo {\n");
    
    sb.append("    postConfig: ").append(toIndentedString(postConfig)).append("\n");
    sb.append("    postOutage: ").append(toIndentedString(postOutage)).append("\n");
    sb.append("    postStream: ").append(toIndentedString(postStream)).append("\n");
    sb.append("    putSensor: ").append(toIndentedString(putSensor)).append("\n");
    sb.append("    getSensor: ").append(toIndentedString(getSensor)).append("\n");
    sb.append("    getConfig: ").append(toIndentedString(getConfig)).append("\n");
    sb.append("    getStatus: ").append(toIndentedString(getStatus)).append("\n");
    sb.append("    getRootCause: ").append(toIndentedString(getRootCause)).append("\n");
    sb.append("    getAmberSummary: ").append(toIndentedString(getAmberSummary)).append("\n");
    sb.append("    postPretrain: ").append(toIndentedString(postPretrain)).append("\n");
    sb.append("    getPretrain: ").append(toIndentedString(getPretrain)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
