/*
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * FusionConfig
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-01-13T09:54:04.469994-06:00[America/Chicago]")
public class FusionConfig {
  public static final String SERIALIZED_NAME_LABEL = "label";
  @SerializedName(SERIALIZED_NAME_LABEL)
  private String label;

  /**
   * policy for submitting sensor fusion vector when this feature is updated. One of \&quot;submit\&quot;, \&quot;nosubmit\&quot; (defaults to \&quot;submit\&quot;)
   */
  @JsonAdapter(SubmitRuleEnum.Adapter.class)
  public enum SubmitRuleEnum {
    SUBMIT("submit"),
    
    NOSUBMIT("nosubmit");

    private String value;

    SubmitRuleEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static SubmitRuleEnum fromValue(String value) {
      for (SubmitRuleEnum b : SubmitRuleEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<SubmitRuleEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SubmitRuleEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public SubmitRuleEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return SubmitRuleEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_SUBMIT_RULE = "submitRule";
  @SerializedName(SERIALIZED_NAME_SUBMIT_RULE)
  private SubmitRuleEnum submitRule;

  public FusionConfig() {
  }

  public FusionConfig label(String label) {
    
    this.label = label;
    return this;
  }

   /**
   * label associated with feature
   * @return label
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "label associated with feature")

  public String getLabel() {
    return label;
  }


  public void setLabel(String label) {
    this.label = label;
  }


  public FusionConfig submitRule(SubmitRuleEnum submitRule) {
    
    this.submitRule = submitRule;
    return this;
  }

   /**
   * policy for submitting sensor fusion vector when this feature is updated. One of \&quot;submit\&quot;, \&quot;nosubmit\&quot; (defaults to \&quot;submit\&quot;)
   * @return submitRule
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "policy for submitting sensor fusion vector when this feature is updated. One of \"submit\", \"nosubmit\" (defaults to \"submit\")")

  public SubmitRuleEnum getSubmitRule() {
    return submitRule;
  }


  public void setSubmitRule(SubmitRuleEnum submitRule) {
    this.submitRule = submitRule;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FusionConfig fusionConfig = (FusionConfig) o;
    return Objects.equals(this.label, fusionConfig.label) &&
        Objects.equals(this.submitRule, fusionConfig.submitRule);
  }

  @Override
  public int hashCode() {
    return Objects.hash(label, submitRule);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FusionConfig {\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    submitRule: ").append(toIndentedString(submitRule)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("label");
    openapiFields.add("submitRule");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("label");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to FusionConfig
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!FusionConfig.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in FusionConfig is not found in the empty JSON string", FusionConfig.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!FusionConfig.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `FusionConfig` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : FusionConfig.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("label").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `label` to be a primitive type in the JSON string but got `%s`", jsonObj.get("label").toString()));
      }
      if ((jsonObj.get("submitRule") != null && !jsonObj.get("submitRule").isJsonNull()) && !jsonObj.get("submitRule").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `submitRule` to be a primitive type in the JSON string but got `%s`", jsonObj.get("submitRule").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!FusionConfig.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'FusionConfig' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<FusionConfig> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(FusionConfig.class));

       return (TypeAdapter<T>) new TypeAdapter<FusionConfig>() {
           @Override
           public void write(JsonWriter out, FusionConfig value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public FusionConfig read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of FusionConfig given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of FusionConfig
  * @throws IOException if the JSON string is invalid with respect to FusionConfig
  */
  public static FusionConfig fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, FusionConfig.class);
  }

 /**
  * Convert an instance of FusionConfig to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

