/*
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.MAmberStatus;
import org.openapitools.client.model.MAutotune;
import org.openapitools.client.model.MBufferStats;
import org.openapitools.client.model.MNano;
import org.openapitools.client.model.MRecentAMs;
import org.openapitools.client.model.MRecentAnalytics;
import org.openapitools.client.model.MRecentIDs;
import org.openapitools.client.model.MRecentSamples;
import org.openapitools.client.model.MRecentTimes;
import org.openapitools.client.model.MStreamingParameters;
import org.openapitools.client.model.MTraining;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * GetSummaryResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-01-10T15:34:16.605003-06:00[America/Chicago]")
public class GetSummaryResponse {
  public static final String SERIALIZED_NAME_MAGIC_NUMBER = "MagicNumber";
  @SerializedName(SERIALIZED_NAME_MAGIC_NUMBER)
  private Integer magicNumber;

  public static final String SERIALIZED_NAME_VERSION_NUMBER = "VersionNumber";
  @SerializedName(SERIALIZED_NAME_VERSION_NUMBER)
  private Integer versionNumber;

  public static final String SERIALIZED_NAME_M_NANO = "m_Nano";
  @SerializedName(SERIALIZED_NAME_M_NANO)
  private MNano mNano;

  public static final String SERIALIZED_NAME_M_BUFFER_STATS = "m_BufferStats";
  @SerializedName(SERIALIZED_NAME_M_BUFFER_STATS)
  private MBufferStats mBufferStats;

  public static final String SERIALIZED_NAME_M_AUTOTUNE = "m_Autotune";
  @SerializedName(SERIALIZED_NAME_M_AUTOTUNE)
  private MAutotune mAutotune;

  public static final String SERIALIZED_NAME_M_AUTOTUNING_ELBOW_CLUSTER_COUNTS = "m_AutotuningElbowClusterCounts";
  @SerializedName(SERIALIZED_NAME_M_AUTOTUNING_ELBOW_CLUSTER_COUNTS)
  private List<Integer> mAutotuningElbowClusterCounts = new ArrayList<>();

  public static final String SERIALIZED_NAME_M_AUTOTUNING_ELBOW_P_V_ARRAY = "m_AutotuningElbowPVArray";
  @SerializedName(SERIALIZED_NAME_M_AUTOTUNING_ELBOW_P_V_ARRAY)
  private List<Float> mAutotuningElbowPVArray = new ArrayList<>();

  public static final String SERIALIZED_NAME_M_STREAMING_PARAMETERS = "m_StreamingParameters";
  @SerializedName(SERIALIZED_NAME_M_STREAMING_PARAMETERS)
  private MStreamingParameters mStreamingParameters;

  public static final String SERIALIZED_NAME_M_AMBER_STATUS = "m_AmberStatus";
  @SerializedName(SERIALIZED_NAME_M_AMBER_STATUS)
  private MAmberStatus mAmberStatus;

  public static final String SERIALIZED_NAME_M_TRAINING = "m_Training";
  @SerializedName(SERIALIZED_NAME_M_TRAINING)
  private MTraining mTraining;

  public static final String SERIALIZED_NAME_M_ANOMALY_THRESHOLD = "m_AnomalyThreshold";
  @SerializedName(SERIALIZED_NAME_M_ANOMALY_THRESHOLD)
  private Integer mAnomalyThreshold;

  public static final String SERIALIZED_NAME_M_AMBER_WARNING_CRITICAL_VALUE = "m_AmberWarningCriticalValue";
  @SerializedName(SERIALIZED_NAME_M_AMBER_WARNING_CRITICAL_VALUE)
  private Integer mAmberWarningCriticalValue;

  public static final String SERIALIZED_NAME_M_AMBER_ALERT_CRITICAL_VALUE = "m_AmberAlertCriticalValue";
  @SerializedName(SERIALIZED_NAME_M_AMBER_ALERT_CRITICAL_VALUE)
  private Integer mAmberAlertCriticalValue;

  public static final String SERIALIZED_NAME_M_ERROR_STRING_BUFFER = "m_ErrorStringBuffer";
  @SerializedName(SERIALIZED_NAME_M_ERROR_STRING_BUFFER)
  private String mErrorStringBuffer;

  public static final String SERIALIZED_NAME_M_CLUSTERING_PARAMETERS_INITIALIZED = "m_ClusteringParametersInitialized";
  @SerializedName(SERIALIZED_NAME_M_CLUSTERING_PARAMETERS_INITIALIZED)
  private Boolean mClusteringParametersInitialized;

  public static final String SERIALIZED_NAME_M_STREAMING_MODE = "m_StreamingMode";
  @SerializedName(SERIALIZED_NAME_M_STREAMING_MODE)
  private Boolean mStreamingMode;

  public static final String SERIALIZED_NAME_M_STREAMING_MODE_STATUS = "m_StreamingModeStatus";
  @SerializedName(SERIALIZED_NAME_M_STREAMING_MODE_STATUS)
  private Integer mStreamingModeStatus;

  public static final String SERIALIZED_NAME_M_MODIFIED_AT = "m_ModifiedAt";
  @SerializedName(SERIALIZED_NAME_M_MODIFIED_AT)
  private Integer mModifiedAt;

  public static final String SERIALIZED_NAME_M_ANOMALY_METRIC_BY_ANOMALY_COUNT = "m_AnomalyMetricByAnomalyCount";
  @SerializedName(SERIALIZED_NAME_M_ANOMALY_METRIC_BY_ANOMALY_COUNT)
  private List<Float> mAnomalyMetricByAnomalyCount = null;

  public static final String SERIALIZED_NAME_M_RECENT_ANOMALY_COUNT = "m_RecentAnomalyCount";
  @SerializedName(SERIALIZED_NAME_M_RECENT_ANOMALY_COUNT)
  private Integer mRecentAnomalyCount;

  public static final String SERIALIZED_NAME_M_RESULTS_I_D_ARRAY = "m_ResultsIDArray";
  @SerializedName(SERIALIZED_NAME_M_RESULTS_I_D_ARRAY)
  private List<Integer> mResultsIDArray = null;

  public static final String SERIALIZED_NAME_M_TRAINING_SAMPLES = "m_TrainingSamples";
  @SerializedName(SERIALIZED_NAME_M_TRAINING_SAMPLES)
  private MRecentSamples mTrainingSamples;

  public static final String SERIALIZED_NAME_M_RECENT_SAMPLES = "m_RecentSamples";
  @SerializedName(SERIALIZED_NAME_M_RECENT_SAMPLES)
  private MRecentSamples mRecentSamples;

  public static final String SERIALIZED_NAME_M_RECENT_RAW_SAMPLES = "m_RecentRawSamples";
  @SerializedName(SERIALIZED_NAME_M_RECENT_RAW_SAMPLES)
  private MRecentSamples mRecentRawSamples;

  public static final String SERIALIZED_NAME_M_RECENT_TIMES = "m_RecentTimes";
  @SerializedName(SERIALIZED_NAME_M_RECENT_TIMES)
  private MRecentTimes mRecentTimes;

  public static final String SERIALIZED_NAME_M_RECENT_S_IS = "m_RecentSIs";
  @SerializedName(SERIALIZED_NAME_M_RECENT_S_IS)
  private MRecentAnalytics mRecentSIs;

  public static final String SERIALIZED_NAME_M_RECENT_R_IS = "m_RecentRIs";
  @SerializedName(SERIALIZED_NAME_M_RECENT_R_IS)
  private MRecentAnalytics mRecentRIs;

  public static final String SERIALIZED_NAME_M_RECENT_A_DS = "m_RecentADs";
  @SerializedName(SERIALIZED_NAME_M_RECENT_A_DS)
  private MRecentAnalytics mRecentADs;

  public static final String SERIALIZED_NAME_M_RECENT_A_HS = "m_RecentAHs";
  @SerializedName(SERIALIZED_NAME_M_RECENT_A_HS)
  private MRecentAnalytics mRecentAHs;

  public static final String SERIALIZED_NAME_M_RECENT_I_DS = "m_RecentIDs";
  @SerializedName(SERIALIZED_NAME_M_RECENT_I_DS)
  private MRecentIDs mRecentIDs;

  public static final String SERIALIZED_NAME_M_RECENT_A_MS = "m_RecentAMs";
  @SerializedName(SERIALIZED_NAME_M_RECENT_A_MS)
  private MRecentAMs mRecentAMs;

  public static final String SERIALIZED_NAME_M_RECENT_A_WS = "m_RecentAWs";
  @SerializedName(SERIALIZED_NAME_M_RECENT_A_WS)
  private MRecentAnalytics mRecentAWs;

  public GetSummaryResponse() {
  }

  public GetSummaryResponse magicNumber(Integer magicNumber) {
    
    this.magicNumber = magicNumber;
    return this;
  }

   /**
   * Get magicNumber
   * @return magicNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getMagicNumber() {
    return magicNumber;
  }


  public void setMagicNumber(Integer magicNumber) {
    this.magicNumber = magicNumber;
  }


  public GetSummaryResponse versionNumber(Integer versionNumber) {
    
    this.versionNumber = versionNumber;
    return this;
  }

   /**
   * Get versionNumber
   * @return versionNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getVersionNumber() {
    return versionNumber;
  }


  public void setVersionNumber(Integer versionNumber) {
    this.versionNumber = versionNumber;
  }


  public GetSummaryResponse mNano(MNano mNano) {
    
    this.mNano = mNano;
    return this;
  }

   /**
   * Get mNano
   * @return mNano
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public MNano getmNano() {
    return mNano;
  }


  public void setmNano(MNano mNano) {
    this.mNano = mNano;
  }


  public GetSummaryResponse mBufferStats(MBufferStats mBufferStats) {
    
    this.mBufferStats = mBufferStats;
    return this;
  }

   /**
   * Get mBufferStats
   * @return mBufferStats
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public MBufferStats getmBufferStats() {
    return mBufferStats;
  }


  public void setmBufferStats(MBufferStats mBufferStats) {
    this.mBufferStats = mBufferStats;
  }


  public GetSummaryResponse mAutotune(MAutotune mAutotune) {
    
    this.mAutotune = mAutotune;
    return this;
  }

   /**
   * Get mAutotune
   * @return mAutotune
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public MAutotune getmAutotune() {
    return mAutotune;
  }


  public void setmAutotune(MAutotune mAutotune) {
    this.mAutotune = mAutotune;
  }


  public GetSummaryResponse mAutotuningElbowClusterCounts(List<Integer> mAutotuningElbowClusterCounts) {
    
    this.mAutotuningElbowClusterCounts = mAutotuningElbowClusterCounts;
    return this;
  }

  public GetSummaryResponse addMAutotuningElbowClusterCountsItem(Integer mAutotuningElbowClusterCountsItem) {
    this.mAutotuningElbowClusterCounts.add(mAutotuningElbowClusterCountsItem);
    return this;
  }

   /**
   * Get mAutotuningElbowClusterCounts
   * @return mAutotuningElbowClusterCounts
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public List<Integer> getmAutotuningElbowClusterCounts() {
    return mAutotuningElbowClusterCounts;
  }


  public void setmAutotuningElbowClusterCounts(List<Integer> mAutotuningElbowClusterCounts) {
    this.mAutotuningElbowClusterCounts = mAutotuningElbowClusterCounts;
  }


  public GetSummaryResponse mAutotuningElbowPVArray(List<Float> mAutotuningElbowPVArray) {
    
    this.mAutotuningElbowPVArray = mAutotuningElbowPVArray;
    return this;
  }

  public GetSummaryResponse addMAutotuningElbowPVArrayItem(Float mAutotuningElbowPVArrayItem) {
    this.mAutotuningElbowPVArray.add(mAutotuningElbowPVArrayItem);
    return this;
  }

   /**
   * Get mAutotuningElbowPVArray
   * @return mAutotuningElbowPVArray
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public List<Float> getmAutotuningElbowPVArray() {
    return mAutotuningElbowPVArray;
  }


  public void setmAutotuningElbowPVArray(List<Float> mAutotuningElbowPVArray) {
    this.mAutotuningElbowPVArray = mAutotuningElbowPVArray;
  }


  public GetSummaryResponse mStreamingParameters(MStreamingParameters mStreamingParameters) {
    
    this.mStreamingParameters = mStreamingParameters;
    return this;
  }

   /**
   * Get mStreamingParameters
   * @return mStreamingParameters
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public MStreamingParameters getmStreamingParameters() {
    return mStreamingParameters;
  }


  public void setmStreamingParameters(MStreamingParameters mStreamingParameters) {
    this.mStreamingParameters = mStreamingParameters;
  }


  public GetSummaryResponse mAmberStatus(MAmberStatus mAmberStatus) {
    
    this.mAmberStatus = mAmberStatus;
    return this;
  }

   /**
   * Get mAmberStatus
   * @return mAmberStatus
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public MAmberStatus getmAmberStatus() {
    return mAmberStatus;
  }


  public void setmAmberStatus(MAmberStatus mAmberStatus) {
    this.mAmberStatus = mAmberStatus;
  }


  public GetSummaryResponse mTraining(MTraining mTraining) {
    
    this.mTraining = mTraining;
    return this;
  }

   /**
   * Get mTraining
   * @return mTraining
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public MTraining getmTraining() {
    return mTraining;
  }


  public void setmTraining(MTraining mTraining) {
    this.mTraining = mTraining;
  }


  public GetSummaryResponse mAnomalyThreshold(Integer mAnomalyThreshold) {
    
    this.mAnomalyThreshold = mAnomalyThreshold;
    return this;
  }

   /**
   * Get mAnomalyThreshold
   * @return mAnomalyThreshold
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Integer getmAnomalyThreshold() {
    return mAnomalyThreshold;
  }


  public void setmAnomalyThreshold(Integer mAnomalyThreshold) {
    this.mAnomalyThreshold = mAnomalyThreshold;
  }


  public GetSummaryResponse mAmberWarningCriticalValue(Integer mAmberWarningCriticalValue) {
    
    this.mAmberWarningCriticalValue = mAmberWarningCriticalValue;
    return this;
  }

   /**
   * Get mAmberWarningCriticalValue
   * @return mAmberWarningCriticalValue
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Integer getmAmberWarningCriticalValue() {
    return mAmberWarningCriticalValue;
  }


  public void setmAmberWarningCriticalValue(Integer mAmberWarningCriticalValue) {
    this.mAmberWarningCriticalValue = mAmberWarningCriticalValue;
  }


  public GetSummaryResponse mAmberAlertCriticalValue(Integer mAmberAlertCriticalValue) {
    
    this.mAmberAlertCriticalValue = mAmberAlertCriticalValue;
    return this;
  }

   /**
   * Get mAmberAlertCriticalValue
   * @return mAmberAlertCriticalValue
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Integer getmAmberAlertCriticalValue() {
    return mAmberAlertCriticalValue;
  }


  public void setmAmberAlertCriticalValue(Integer mAmberAlertCriticalValue) {
    this.mAmberAlertCriticalValue = mAmberAlertCriticalValue;
  }


  public GetSummaryResponse mErrorStringBuffer(String mErrorStringBuffer) {
    
    this.mErrorStringBuffer = mErrorStringBuffer;
    return this;
  }

   /**
   * Get mErrorStringBuffer
   * @return mErrorStringBuffer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getmErrorStringBuffer() {
    return mErrorStringBuffer;
  }


  public void setmErrorStringBuffer(String mErrorStringBuffer) {
    this.mErrorStringBuffer = mErrorStringBuffer;
  }


  public GetSummaryResponse mClusteringParametersInitialized(Boolean mClusteringParametersInitialized) {
    
    this.mClusteringParametersInitialized = mClusteringParametersInitialized;
    return this;
  }

   /**
   * Get mClusteringParametersInitialized
   * @return mClusteringParametersInitialized
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getmClusteringParametersInitialized() {
    return mClusteringParametersInitialized;
  }


  public void setmClusteringParametersInitialized(Boolean mClusteringParametersInitialized) {
    this.mClusteringParametersInitialized = mClusteringParametersInitialized;
  }


  public GetSummaryResponse mStreamingMode(Boolean mStreamingMode) {
    
    this.mStreamingMode = mStreamingMode;
    return this;
  }

   /**
   * Get mStreamingMode
   * @return mStreamingMode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getmStreamingMode() {
    return mStreamingMode;
  }


  public void setmStreamingMode(Boolean mStreamingMode) {
    this.mStreamingMode = mStreamingMode;
  }


  public GetSummaryResponse mStreamingModeStatus(Integer mStreamingModeStatus) {
    
    this.mStreamingModeStatus = mStreamingModeStatus;
    return this;
  }

   /**
   * Get mStreamingModeStatus
   * @return mStreamingModeStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getmStreamingModeStatus() {
    return mStreamingModeStatus;
  }


  public void setmStreamingModeStatus(Integer mStreamingModeStatus) {
    this.mStreamingModeStatus = mStreamingModeStatus;
  }


  public GetSummaryResponse mModifiedAt(Integer mModifiedAt) {
    
    this.mModifiedAt = mModifiedAt;
    return this;
  }

   /**
   * Get mModifiedAt
   * @return mModifiedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getmModifiedAt() {
    return mModifiedAt;
  }


  public void setmModifiedAt(Integer mModifiedAt) {
    this.mModifiedAt = mModifiedAt;
  }


  public GetSummaryResponse mAnomalyMetricByAnomalyCount(List<Float> mAnomalyMetricByAnomalyCount) {
    
    this.mAnomalyMetricByAnomalyCount = mAnomalyMetricByAnomalyCount;
    return this;
  }

  public GetSummaryResponse addMAnomalyMetricByAnomalyCountItem(Float mAnomalyMetricByAnomalyCountItem) {
    if (this.mAnomalyMetricByAnomalyCount == null) {
      this.mAnomalyMetricByAnomalyCount = new ArrayList<>();
    }
    this.mAnomalyMetricByAnomalyCount.add(mAnomalyMetricByAnomalyCountItem);
    return this;
  }

   /**
   * Get mAnomalyMetricByAnomalyCount
   * @return mAnomalyMetricByAnomalyCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Float> getmAnomalyMetricByAnomalyCount() {
    return mAnomalyMetricByAnomalyCount;
  }


  public void setmAnomalyMetricByAnomalyCount(List<Float> mAnomalyMetricByAnomalyCount) {
    this.mAnomalyMetricByAnomalyCount = mAnomalyMetricByAnomalyCount;
  }


  public GetSummaryResponse mRecentAnomalyCount(Integer mRecentAnomalyCount) {
    
    this.mRecentAnomalyCount = mRecentAnomalyCount;
    return this;
  }

   /**
   * Get mRecentAnomalyCount
   * @return mRecentAnomalyCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getmRecentAnomalyCount() {
    return mRecentAnomalyCount;
  }


  public void setmRecentAnomalyCount(Integer mRecentAnomalyCount) {
    this.mRecentAnomalyCount = mRecentAnomalyCount;
  }


  public GetSummaryResponse mResultsIDArray(List<Integer> mResultsIDArray) {
    
    this.mResultsIDArray = mResultsIDArray;
    return this;
  }

  public GetSummaryResponse addMResultsIDArrayItem(Integer mResultsIDArrayItem) {
    if (this.mResultsIDArray == null) {
      this.mResultsIDArray = new ArrayList<>();
    }
    this.mResultsIDArray.add(mResultsIDArrayItem);
    return this;
  }

   /**
   * Get mResultsIDArray
   * @return mResultsIDArray
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Integer> getmResultsIDArray() {
    return mResultsIDArray;
  }


  public void setmResultsIDArray(List<Integer> mResultsIDArray) {
    this.mResultsIDArray = mResultsIDArray;
  }


  public GetSummaryResponse mTrainingSamples(MRecentSamples mTrainingSamples) {
    
    this.mTrainingSamples = mTrainingSamples;
    return this;
  }

   /**
   * Get mTrainingSamples
   * @return mTrainingSamples
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public MRecentSamples getmTrainingSamples() {
    return mTrainingSamples;
  }


  public void setmTrainingSamples(MRecentSamples mTrainingSamples) {
    this.mTrainingSamples = mTrainingSamples;
  }


  public GetSummaryResponse mRecentSamples(MRecentSamples mRecentSamples) {
    
    this.mRecentSamples = mRecentSamples;
    return this;
  }

   /**
   * Get mRecentSamples
   * @return mRecentSamples
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public MRecentSamples getmRecentSamples() {
    return mRecentSamples;
  }


  public void setmRecentSamples(MRecentSamples mRecentSamples) {
    this.mRecentSamples = mRecentSamples;
  }


  public GetSummaryResponse mRecentRawSamples(MRecentSamples mRecentRawSamples) {
    
    this.mRecentRawSamples = mRecentRawSamples;
    return this;
  }

   /**
   * Get mRecentRawSamples
   * @return mRecentRawSamples
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public MRecentSamples getmRecentRawSamples() {
    return mRecentRawSamples;
  }


  public void setmRecentRawSamples(MRecentSamples mRecentRawSamples) {
    this.mRecentRawSamples = mRecentRawSamples;
  }


  public GetSummaryResponse mRecentTimes(MRecentTimes mRecentTimes) {
    
    this.mRecentTimes = mRecentTimes;
    return this;
  }

   /**
   * Get mRecentTimes
   * @return mRecentTimes
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public MRecentTimes getmRecentTimes() {
    return mRecentTimes;
  }


  public void setmRecentTimes(MRecentTimes mRecentTimes) {
    this.mRecentTimes = mRecentTimes;
  }


  public GetSummaryResponse mRecentSIs(MRecentAnalytics mRecentSIs) {
    
    this.mRecentSIs = mRecentSIs;
    return this;
  }

   /**
   * Get mRecentSIs
   * @return mRecentSIs
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public MRecentAnalytics getmRecentSIs() {
    return mRecentSIs;
  }


  public void setmRecentSIs(MRecentAnalytics mRecentSIs) {
    this.mRecentSIs = mRecentSIs;
  }


  public GetSummaryResponse mRecentRIs(MRecentAnalytics mRecentRIs) {
    
    this.mRecentRIs = mRecentRIs;
    return this;
  }

   /**
   * Get mRecentRIs
   * @return mRecentRIs
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public MRecentAnalytics getmRecentRIs() {
    return mRecentRIs;
  }


  public void setmRecentRIs(MRecentAnalytics mRecentRIs) {
    this.mRecentRIs = mRecentRIs;
  }


  public GetSummaryResponse mRecentADs(MRecentAnalytics mRecentADs) {
    
    this.mRecentADs = mRecentADs;
    return this;
  }

   /**
   * Get mRecentADs
   * @return mRecentADs
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public MRecentAnalytics getmRecentADs() {
    return mRecentADs;
  }


  public void setmRecentADs(MRecentAnalytics mRecentADs) {
    this.mRecentADs = mRecentADs;
  }


  public GetSummaryResponse mRecentAHs(MRecentAnalytics mRecentAHs) {
    
    this.mRecentAHs = mRecentAHs;
    return this;
  }

   /**
   * Get mRecentAHs
   * @return mRecentAHs
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public MRecentAnalytics getmRecentAHs() {
    return mRecentAHs;
  }


  public void setmRecentAHs(MRecentAnalytics mRecentAHs) {
    this.mRecentAHs = mRecentAHs;
  }


  public GetSummaryResponse mRecentIDs(MRecentIDs mRecentIDs) {
    
    this.mRecentIDs = mRecentIDs;
    return this;
  }

   /**
   * Get mRecentIDs
   * @return mRecentIDs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public MRecentIDs getmRecentIDs() {
    return mRecentIDs;
  }


  public void setmRecentIDs(MRecentIDs mRecentIDs) {
    this.mRecentIDs = mRecentIDs;
  }


  public GetSummaryResponse mRecentAMs(MRecentAMs mRecentAMs) {
    
    this.mRecentAMs = mRecentAMs;
    return this;
  }

   /**
   * Get mRecentAMs
   * @return mRecentAMs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public MRecentAMs getmRecentAMs() {
    return mRecentAMs;
  }


  public void setmRecentAMs(MRecentAMs mRecentAMs) {
    this.mRecentAMs = mRecentAMs;
  }


  public GetSummaryResponse mRecentAWs(MRecentAnalytics mRecentAWs) {
    
    this.mRecentAWs = mRecentAWs;
    return this;
  }

   /**
   * Get mRecentAWs
   * @return mRecentAWs
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public MRecentAnalytics getmRecentAWs() {
    return mRecentAWs;
  }


  public void setmRecentAWs(MRecentAnalytics mRecentAWs) {
    this.mRecentAWs = mRecentAWs;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetSummaryResponse getSummaryResponse = (GetSummaryResponse) o;
    return Objects.equals(this.magicNumber, getSummaryResponse.magicNumber) &&
        Objects.equals(this.versionNumber, getSummaryResponse.versionNumber) &&
        Objects.equals(this.mNano, getSummaryResponse.mNano) &&
        Objects.equals(this.mBufferStats, getSummaryResponse.mBufferStats) &&
        Objects.equals(this.mAutotune, getSummaryResponse.mAutotune) &&
        Objects.equals(this.mAutotuningElbowClusterCounts, getSummaryResponse.mAutotuningElbowClusterCounts) &&
        Objects.equals(this.mAutotuningElbowPVArray, getSummaryResponse.mAutotuningElbowPVArray) &&
        Objects.equals(this.mStreamingParameters, getSummaryResponse.mStreamingParameters) &&
        Objects.equals(this.mAmberStatus, getSummaryResponse.mAmberStatus) &&
        Objects.equals(this.mTraining, getSummaryResponse.mTraining) &&
        Objects.equals(this.mAnomalyThreshold, getSummaryResponse.mAnomalyThreshold) &&
        Objects.equals(this.mAmberWarningCriticalValue, getSummaryResponse.mAmberWarningCriticalValue) &&
        Objects.equals(this.mAmberAlertCriticalValue, getSummaryResponse.mAmberAlertCriticalValue) &&
        Objects.equals(this.mErrorStringBuffer, getSummaryResponse.mErrorStringBuffer) &&
        Objects.equals(this.mClusteringParametersInitialized, getSummaryResponse.mClusteringParametersInitialized) &&
        Objects.equals(this.mStreamingMode, getSummaryResponse.mStreamingMode) &&
        Objects.equals(this.mStreamingModeStatus, getSummaryResponse.mStreamingModeStatus) &&
        Objects.equals(this.mModifiedAt, getSummaryResponse.mModifiedAt) &&
        Objects.equals(this.mAnomalyMetricByAnomalyCount, getSummaryResponse.mAnomalyMetricByAnomalyCount) &&
        Objects.equals(this.mRecentAnomalyCount, getSummaryResponse.mRecentAnomalyCount) &&
        Objects.equals(this.mResultsIDArray, getSummaryResponse.mResultsIDArray) &&
        Objects.equals(this.mTrainingSamples, getSummaryResponse.mTrainingSamples) &&
        Objects.equals(this.mRecentSamples, getSummaryResponse.mRecentSamples) &&
        Objects.equals(this.mRecentRawSamples, getSummaryResponse.mRecentRawSamples) &&
        Objects.equals(this.mRecentTimes, getSummaryResponse.mRecentTimes) &&
        Objects.equals(this.mRecentSIs, getSummaryResponse.mRecentSIs) &&
        Objects.equals(this.mRecentRIs, getSummaryResponse.mRecentRIs) &&
        Objects.equals(this.mRecentADs, getSummaryResponse.mRecentADs) &&
        Objects.equals(this.mRecentAHs, getSummaryResponse.mRecentAHs) &&
        Objects.equals(this.mRecentIDs, getSummaryResponse.mRecentIDs) &&
        Objects.equals(this.mRecentAMs, getSummaryResponse.mRecentAMs) &&
        Objects.equals(this.mRecentAWs, getSummaryResponse.mRecentAWs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(magicNumber, versionNumber, mNano, mBufferStats, mAutotune, mAutotuningElbowClusterCounts, mAutotuningElbowPVArray, mStreamingParameters, mAmberStatus, mTraining, mAnomalyThreshold, mAmberWarningCriticalValue, mAmberAlertCriticalValue, mErrorStringBuffer, mClusteringParametersInitialized, mStreamingMode, mStreamingModeStatus, mModifiedAt, mAnomalyMetricByAnomalyCount, mRecentAnomalyCount, mResultsIDArray, mTrainingSamples, mRecentSamples, mRecentRawSamples, mRecentTimes, mRecentSIs, mRecentRIs, mRecentADs, mRecentAHs, mRecentIDs, mRecentAMs, mRecentAWs);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetSummaryResponse {\n");
    sb.append("    magicNumber: ").append(toIndentedString(magicNumber)).append("\n");
    sb.append("    versionNumber: ").append(toIndentedString(versionNumber)).append("\n");
    sb.append("    mNano: ").append(toIndentedString(mNano)).append("\n");
    sb.append("    mBufferStats: ").append(toIndentedString(mBufferStats)).append("\n");
    sb.append("    mAutotune: ").append(toIndentedString(mAutotune)).append("\n");
    sb.append("    mAutotuningElbowClusterCounts: ").append(toIndentedString(mAutotuningElbowClusterCounts)).append("\n");
    sb.append("    mAutotuningElbowPVArray: ").append(toIndentedString(mAutotuningElbowPVArray)).append("\n");
    sb.append("    mStreamingParameters: ").append(toIndentedString(mStreamingParameters)).append("\n");
    sb.append("    mAmberStatus: ").append(toIndentedString(mAmberStatus)).append("\n");
    sb.append("    mTraining: ").append(toIndentedString(mTraining)).append("\n");
    sb.append("    mAnomalyThreshold: ").append(toIndentedString(mAnomalyThreshold)).append("\n");
    sb.append("    mAmberWarningCriticalValue: ").append(toIndentedString(mAmberWarningCriticalValue)).append("\n");
    sb.append("    mAmberAlertCriticalValue: ").append(toIndentedString(mAmberAlertCriticalValue)).append("\n");
    sb.append("    mErrorStringBuffer: ").append(toIndentedString(mErrorStringBuffer)).append("\n");
    sb.append("    mClusteringParametersInitialized: ").append(toIndentedString(mClusteringParametersInitialized)).append("\n");
    sb.append("    mStreamingMode: ").append(toIndentedString(mStreamingMode)).append("\n");
    sb.append("    mStreamingModeStatus: ").append(toIndentedString(mStreamingModeStatus)).append("\n");
    sb.append("    mModifiedAt: ").append(toIndentedString(mModifiedAt)).append("\n");
    sb.append("    mAnomalyMetricByAnomalyCount: ").append(toIndentedString(mAnomalyMetricByAnomalyCount)).append("\n");
    sb.append("    mRecentAnomalyCount: ").append(toIndentedString(mRecentAnomalyCount)).append("\n");
    sb.append("    mResultsIDArray: ").append(toIndentedString(mResultsIDArray)).append("\n");
    sb.append("    mTrainingSamples: ").append(toIndentedString(mTrainingSamples)).append("\n");
    sb.append("    mRecentSamples: ").append(toIndentedString(mRecentSamples)).append("\n");
    sb.append("    mRecentRawSamples: ").append(toIndentedString(mRecentRawSamples)).append("\n");
    sb.append("    mRecentTimes: ").append(toIndentedString(mRecentTimes)).append("\n");
    sb.append("    mRecentSIs: ").append(toIndentedString(mRecentSIs)).append("\n");
    sb.append("    mRecentRIs: ").append(toIndentedString(mRecentRIs)).append("\n");
    sb.append("    mRecentADs: ").append(toIndentedString(mRecentADs)).append("\n");
    sb.append("    mRecentAHs: ").append(toIndentedString(mRecentAHs)).append("\n");
    sb.append("    mRecentIDs: ").append(toIndentedString(mRecentIDs)).append("\n");
    sb.append("    mRecentAMs: ").append(toIndentedString(mRecentAMs)).append("\n");
    sb.append("    mRecentAWs: ").append(toIndentedString(mRecentAWs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("MagicNumber");
    openapiFields.add("VersionNumber");
    openapiFields.add("m_Nano");
    openapiFields.add("m_BufferStats");
    openapiFields.add("m_Autotune");
    openapiFields.add("m_AutotuningElbowClusterCounts");
    openapiFields.add("m_AutotuningElbowPVArray");
    openapiFields.add("m_StreamingParameters");
    openapiFields.add("m_AmberStatus");
    openapiFields.add("m_Training");
    openapiFields.add("m_AnomalyThreshold");
    openapiFields.add("m_AmberWarningCriticalValue");
    openapiFields.add("m_AmberAlertCriticalValue");
    openapiFields.add("m_ErrorStringBuffer");
    openapiFields.add("m_ClusteringParametersInitialized");
    openapiFields.add("m_StreamingMode");
    openapiFields.add("m_StreamingModeStatus");
    openapiFields.add("m_ModifiedAt");
    openapiFields.add("m_AnomalyMetricByAnomalyCount");
    openapiFields.add("m_RecentAnomalyCount");
    openapiFields.add("m_ResultsIDArray");
    openapiFields.add("m_TrainingSamples");
    openapiFields.add("m_RecentSamples");
    openapiFields.add("m_RecentRawSamples");
    openapiFields.add("m_RecentTimes");
    openapiFields.add("m_RecentSIs");
    openapiFields.add("m_RecentRIs");
    openapiFields.add("m_RecentADs");
    openapiFields.add("m_RecentAHs");
    openapiFields.add("m_RecentIDs");
    openapiFields.add("m_RecentAMs");
    openapiFields.add("m_RecentAWs");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("m_Nano");
    openapiRequiredFields.add("m_Autotune");
    openapiRequiredFields.add("m_AutotuningElbowClusterCounts");
    openapiRequiredFields.add("m_AutotuningElbowPVArray");
    openapiRequiredFields.add("m_StreamingParameters");
    openapiRequiredFields.add("m_AmberStatus");
    openapiRequiredFields.add("m_Training");
    openapiRequiredFields.add("m_AnomalyThreshold");
    openapiRequiredFields.add("m_AmberWarningCriticalValue");
    openapiRequiredFields.add("m_AmberAlertCriticalValue");
    openapiRequiredFields.add("m_RecentSamples");
    openapiRequiredFields.add("m_RecentRawSamples");
    openapiRequiredFields.add("m_RecentTimes");
    openapiRequiredFields.add("m_RecentSIs");
    openapiRequiredFields.add("m_RecentRIs");
    openapiRequiredFields.add("m_RecentADs");
    openapiRequiredFields.add("m_RecentAHs");
    openapiRequiredFields.add("m_RecentAWs");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to GetSummaryResponse
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!GetSummaryResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GetSummaryResponse is not found in the empty JSON string", GetSummaryResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!GetSummaryResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GetSummaryResponse` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : GetSummaryResponse.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      // validate the required field `m_Nano`
      MNano.validateJsonObject(jsonObj.getAsJsonObject("m_Nano"));
      // validate the optional field `m_BufferStats`
      if (jsonObj.get("m_BufferStats") != null && !jsonObj.get("m_BufferStats").isJsonNull()) {
        MBufferStats.validateJsonObject(jsonObj.getAsJsonObject("m_BufferStats"));
      }
      // validate the required field `m_Autotune`
      MAutotune.validateJsonObject(jsonObj.getAsJsonObject("m_Autotune"));
      // ensure the required json array is present
      if (jsonObj.get("m_AutotuningElbowClusterCounts") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("m_AutotuningElbowClusterCounts").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `m_AutotuningElbowClusterCounts` to be an array in the JSON string but got `%s`", jsonObj.get("m_AutotuningElbowClusterCounts").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("m_AutotuningElbowPVArray") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("m_AutotuningElbowPVArray").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `m_AutotuningElbowPVArray` to be an array in the JSON string but got `%s`", jsonObj.get("m_AutotuningElbowPVArray").toString()));
      }
      // validate the required field `m_StreamingParameters`
      MStreamingParameters.validateJsonObject(jsonObj.getAsJsonObject("m_StreamingParameters"));
      // validate the required field `m_AmberStatus`
      MAmberStatus.validateJsonObject(jsonObj.getAsJsonObject("m_AmberStatus"));
      // validate the required field `m_Training`
      MTraining.validateJsonObject(jsonObj.getAsJsonObject("m_Training"));
      if ((jsonObj.get("m_ErrorStringBuffer") != null && !jsonObj.get("m_ErrorStringBuffer").isJsonNull()) && !jsonObj.get("m_ErrorStringBuffer").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `m_ErrorStringBuffer` to be a primitive type in the JSON string but got `%s`", jsonObj.get("m_ErrorStringBuffer").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("m_AnomalyMetricByAnomalyCount") != null && !jsonObj.get("m_AnomalyMetricByAnomalyCount").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `m_AnomalyMetricByAnomalyCount` to be an array in the JSON string but got `%s`", jsonObj.get("m_AnomalyMetricByAnomalyCount").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("m_ResultsIDArray") != null && !jsonObj.get("m_ResultsIDArray").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `m_ResultsIDArray` to be an array in the JSON string but got `%s`", jsonObj.get("m_ResultsIDArray").toString()));
      }
      // validate the optional field `m_TrainingSamples`
      if (jsonObj.get("m_TrainingSamples") != null && !jsonObj.get("m_TrainingSamples").isJsonNull()) {
        MRecentSamples.validateJsonObject(jsonObj.getAsJsonObject("m_TrainingSamples"));
      }
      // validate the required field `m_RecentSamples`
      MRecentSamples.validateJsonObject(jsonObj.getAsJsonObject("m_RecentSamples"));
      // validate the required field `m_RecentRawSamples`
      MRecentSamples.validateJsonObject(jsonObj.getAsJsonObject("m_RecentRawSamples"));
      // validate the required field `m_RecentTimes`
      MRecentTimes.validateJsonObject(jsonObj.getAsJsonObject("m_RecentTimes"));
      // validate the required field `m_RecentSIs`
      MRecentAnalytics.validateJsonObject(jsonObj.getAsJsonObject("m_RecentSIs"));
      // validate the required field `m_RecentRIs`
      MRecentAnalytics.validateJsonObject(jsonObj.getAsJsonObject("m_RecentRIs"));
      // validate the required field `m_RecentADs`
      MRecentAnalytics.validateJsonObject(jsonObj.getAsJsonObject("m_RecentADs"));
      // validate the required field `m_RecentAHs`
      MRecentAnalytics.validateJsonObject(jsonObj.getAsJsonObject("m_RecentAHs"));
      // validate the optional field `m_RecentIDs`
      if (jsonObj.get("m_RecentIDs") != null && !jsonObj.get("m_RecentIDs").isJsonNull()) {
        MRecentIDs.validateJsonObject(jsonObj.getAsJsonObject("m_RecentIDs"));
      }
      // validate the optional field `m_RecentAMs`
      if (jsonObj.get("m_RecentAMs") != null && !jsonObj.get("m_RecentAMs").isJsonNull()) {
        MRecentAMs.validateJsonObject(jsonObj.getAsJsonObject("m_RecentAMs"));
      }
      // validate the required field `m_RecentAWs`
      MRecentAnalytics.validateJsonObject(jsonObj.getAsJsonObject("m_RecentAWs"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetSummaryResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetSummaryResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetSummaryResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetSummaryResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<GetSummaryResponse>() {
           @Override
           public void write(JsonWriter out, GetSummaryResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetSummaryResponse read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of GetSummaryResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of GetSummaryResponse
  * @throws IOException if the JSON string is invalid with respect to GetSummaryResponse
  */
  public static GetSummaryResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetSummaryResponse.class);
  }

 /**
  * Convert an instance of GetSummaryResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

