/*
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * PostPretrainResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-01-10T15:34:16.605003-06:00[America/Chicago]")
public class PostPretrainResponse {
  public static final String SERIALIZED_NAME_STATE = "state";
  @SerializedName(SERIALIZED_NAME_STATE)
  private String state;

  public static final String SERIALIZED_NAME_AMBER_TRANSACTION = "amberTransaction";
  @SerializedName(SERIALIZED_NAME_AMBER_TRANSACTION)
  private String amberTransaction;

  public static final String SERIALIZED_NAME_AMBER_CHUNK = "amberChunk";
  @SerializedName(SERIALIZED_NAME_AMBER_CHUNK)
  private String amberChunk;

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  private String message;

  public PostPretrainResponse() {
  }

  public PostPretrainResponse state(String state) {
    
    this.state = state;
    return this;
  }

   /**
   * state of pretraining, one of: Chunking, Pretraining, Pretrained, Error
   * @return state
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "state of pretraining, one of: Chunking, Pretraining, Pretrained, Error")

  public String getState() {
    return state;
  }


  public void setState(String state) {
    this.state = state;
  }


  public PostPretrainResponse amberTransaction(String amberTransaction) {
    
    this.amberTransaction = amberTransaction;
    return this;
  }

   /**
   * Get amberTransaction
   * @return amberTransaction
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAmberTransaction() {
    return amberTransaction;
  }


  public void setAmberTransaction(String amberTransaction) {
    this.amberTransaction = amberTransaction;
  }


  public PostPretrainResponse amberChunk(String amberChunk) {
    
    this.amberChunk = amberChunk;
    return this;
  }

   /**
   * Get amberChunk
   * @return amberChunk
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAmberChunk() {
    return amberChunk;
  }


  public void setAmberChunk(String amberChunk) {
    this.amberChunk = amberChunk;
  }


  public PostPretrainResponse message(String message) {
    
    this.message = message;
    return this;
  }

   /**
   * latest pretrain message
   * @return message
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "latest pretrain message")

  public String getMessage() {
    return message;
  }


  public void setMessage(String message) {
    this.message = message;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostPretrainResponse postPretrainResponse = (PostPretrainResponse) o;
    return Objects.equals(this.state, postPretrainResponse.state) &&
        Objects.equals(this.amberTransaction, postPretrainResponse.amberTransaction) &&
        Objects.equals(this.amberChunk, postPretrainResponse.amberChunk) &&
        Objects.equals(this.message, postPretrainResponse.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(state, amberTransaction, amberChunk, message);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostPretrainResponse {\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    amberTransaction: ").append(toIndentedString(amberTransaction)).append("\n");
    sb.append("    amberChunk: ").append(toIndentedString(amberChunk)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("state");
    openapiFields.add("amberTransaction");
    openapiFields.add("amberChunk");
    openapiFields.add("message");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("state");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PostPretrainResponse
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!PostPretrainResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PostPretrainResponse is not found in the empty JSON string", PostPretrainResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!PostPretrainResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PostPretrainResponse` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : PostPretrainResponse.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("state").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `state` to be a primitive type in the JSON string but got `%s`", jsonObj.get("state").toString()));
      }
      if ((jsonObj.get("amberTransaction") != null && !jsonObj.get("amberTransaction").isJsonNull()) && !jsonObj.get("amberTransaction").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `amberTransaction` to be a primitive type in the JSON string but got `%s`", jsonObj.get("amberTransaction").toString()));
      }
      if ((jsonObj.get("amberChunk") != null && !jsonObj.get("amberChunk").isJsonNull()) && !jsonObj.get("amberChunk").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `amberChunk` to be a primitive type in the JSON string but got `%s`", jsonObj.get("amberChunk").toString()));
      }
      if ((jsonObj.get("message") != null && !jsonObj.get("message").isJsonNull()) && !jsonObj.get("message").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `message` to be a primitive type in the JSON string but got `%s`", jsonObj.get("message").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PostPretrainResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PostPretrainResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PostPretrainResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PostPretrainResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<PostPretrainResponse>() {
           @Override
           public void write(JsonWriter out, PostPretrainResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PostPretrainResponse read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PostPretrainResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PostPretrainResponse
  * @throws IOException if the JSON string is invalid with respect to PostPretrainResponse
  */
  public static PostPretrainResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PostPretrainResponse.class);
  }

 /**
  * Convert an instance of PostPretrainResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

