/*
 * Amber API Server
 * Boon Logic Amber API server
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.AnalyticResults;
import org.openapitools.client.model.FusionFeature;
import org.openapitools.client.model.ModelStatus;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * PutDataResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-01-13T15:13:44.158456-06:00[America/Chicago]")
public class PutDataResponse {
  public static final String SERIALIZED_NAME_VECTOR = "vector";
  @SerializedName(SERIALIZED_NAME_VECTOR)
  private List<FusionFeature> vector = null;

  public static final String SERIALIZED_NAME_ANALYTICS = "analytics";
  @SerializedName(SERIALIZED_NAME_ANALYTICS)
  private AnalyticResults analytics;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private ModelStatus status;

  public PutDataResponse() {
  }

  public PutDataResponse vector(List<FusionFeature> vector) {
    
    this.vector = vector;
    return this;
  }

  public PutDataResponse addVectorItem(FusionFeature vectorItem) {
    if (this.vector == null) {
      this.vector = new ArrayList<>();
    }
    this.vector.add(vectorItem);
    return this;
  }

   /**
   * The current fusion vector.
   * @return vector
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The current fusion vector.")

  public List<FusionFeature> getVector() {
    return vector;
  }


  public void setVector(List<FusionFeature> vector) {
    this.vector = vector;
  }


  public PutDataResponse analytics(AnalyticResults analytics) {
    
    this.analytics = analytics;
    return this;
  }

   /**
   * Get analytics
   * @return analytics
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public AnalyticResults getAnalytics() {
    return analytics;
  }


  public void setAnalytics(AnalyticResults analytics) {
    this.analytics = analytics;
  }


  public PutDataResponse status(ModelStatus status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ModelStatus getStatus() {
    return status;
  }


  public void setStatus(ModelStatus status) {
    this.status = status;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PutDataResponse putDataResponse = (PutDataResponse) o;
    return Objects.equals(this.vector, putDataResponse.vector) &&
        Objects.equals(this.analytics, putDataResponse.analytics) &&
        Objects.equals(this.status, putDataResponse.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(vector, analytics, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PutDataResponse {\n");
    sb.append("    vector: ").append(toIndentedString(vector)).append("\n");
    sb.append("    analytics: ").append(toIndentedString(analytics)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("vector");
    openapiFields.add("analytics");
    openapiFields.add("status");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PutDataResponse
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!PutDataResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PutDataResponse is not found in the empty JSON string", PutDataResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!PutDataResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PutDataResponse` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if (jsonObj.get("vector") != null && !jsonObj.get("vector").isJsonNull()) {
        JsonArray jsonArrayvector = jsonObj.getAsJsonArray("vector");
        if (jsonArrayvector != null) {
          // ensure the json data is an array
          if (!jsonObj.get("vector").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `vector` to be an array in the JSON string but got `%s`", jsonObj.get("vector").toString()));
          }

          // validate the optional field `vector` (array)
          for (int i = 0; i < jsonArrayvector.size(); i++) {
            FusionFeature.validateJsonObject(jsonArrayvector.get(i).getAsJsonObject());
          };
        }
      }
      // validate the optional field `analytics`
      if (jsonObj.get("analytics") != null && !jsonObj.get("analytics").isJsonNull()) {
        AnalyticResults.validateJsonObject(jsonObj.getAsJsonObject("analytics"));
      }
      // validate the optional field `status`
      if (jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) {
        ModelStatus.validateJsonObject(jsonObj.getAsJsonObject("status"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PutDataResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PutDataResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PutDataResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PutDataResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<PutDataResponse>() {
           @Override
           public void write(JsonWriter out, PutDataResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PutDataResponse read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PutDataResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PutDataResponse
  * @throws IOException if the JSON string is invalid with respect to PutDataResponse
  */
  public static PutDataResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PutDataResponse.class);
  }

 /**
  * Convert an instance of PutDataResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

