/*
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Version
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-01-10T15:34:16.605003-06:00[America/Chicago]")
public class Version {
  public static final String SERIALIZED_NAME_RELEASE = "release";
  @SerializedName(SERIALIZED_NAME_RELEASE)
  private String release;

  public static final String SERIALIZED_NAME_API_VERSION = "api-version";
  @SerializedName(SERIALIZED_NAME_API_VERSION)
  private String apiVersion;

  public static final String SERIALIZED_NAME_BUILDER = "builder";
  @SerializedName(SERIALIZED_NAME_BUILDER)
  private String builder;

  public static final String SERIALIZED_NAME_EXPERT_API = "expert-api";
  @SerializedName(SERIALIZED_NAME_EXPERT_API)
  private String expertApi;

  public static final String SERIALIZED_NAME_EXPERT_COMMON = "expert-common";
  @SerializedName(SERIALIZED_NAME_EXPERT_COMMON)
  private String expertCommon;

  public static final String SERIALIZED_NAME_NANO_SECURE = "nano-secure";
  @SerializedName(SERIALIZED_NAME_NANO_SECURE)
  private String nanoSecure;

  public static final String SERIALIZED_NAME_SWAGGER_UI = "swagger-ui";
  @SerializedName(SERIALIZED_NAME_SWAGGER_UI)
  private String swaggerUi;

  public Version() {
  }

  public Version release(String release) {
    
    this.release = release;
    return this;
  }

   /**
   * Get release
   * @return release
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getRelease() {
    return release;
  }


  public void setRelease(String release) {
    this.release = release;
  }


  public Version apiVersion(String apiVersion) {
    
    this.apiVersion = apiVersion;
    return this;
  }

   /**
   * Get apiVersion
   * @return apiVersion
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getApiVersion() {
    return apiVersion;
  }


  public void setApiVersion(String apiVersion) {
    this.apiVersion = apiVersion;
  }


  public Version builder(String builder) {
    
    this.builder = builder;
    return this;
  }

   /**
   * Get builder
   * @return builder
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getBuilder() {
    return builder;
  }


  public void setBuilder(String builder) {
    this.builder = builder;
  }


  public Version expertApi(String expertApi) {
    
    this.expertApi = expertApi;
    return this;
  }

   /**
   * Get expertApi
   * @return expertApi
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getExpertApi() {
    return expertApi;
  }


  public void setExpertApi(String expertApi) {
    this.expertApi = expertApi;
  }


  public Version expertCommon(String expertCommon) {
    
    this.expertCommon = expertCommon;
    return this;
  }

   /**
   * Get expertCommon
   * @return expertCommon
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getExpertCommon() {
    return expertCommon;
  }


  public void setExpertCommon(String expertCommon) {
    this.expertCommon = expertCommon;
  }


  public Version nanoSecure(String nanoSecure) {
    
    this.nanoSecure = nanoSecure;
    return this;
  }

   /**
   * Get nanoSecure
   * @return nanoSecure
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getNanoSecure() {
    return nanoSecure;
  }


  public void setNanoSecure(String nanoSecure) {
    this.nanoSecure = nanoSecure;
  }


  public Version swaggerUi(String swaggerUi) {
    
    this.swaggerUi = swaggerUi;
    return this;
  }

   /**
   * Get swaggerUi
   * @return swaggerUi
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getSwaggerUi() {
    return swaggerUi;
  }


  public void setSwaggerUi(String swaggerUi) {
    this.swaggerUi = swaggerUi;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Version version = (Version) o;
    return Objects.equals(this.release, version.release) &&
        Objects.equals(this.apiVersion, version.apiVersion) &&
        Objects.equals(this.builder, version.builder) &&
        Objects.equals(this.expertApi, version.expertApi) &&
        Objects.equals(this.expertCommon, version.expertCommon) &&
        Objects.equals(this.nanoSecure, version.nanoSecure) &&
        Objects.equals(this.swaggerUi, version.swaggerUi);
  }

  @Override
  public int hashCode() {
    return Objects.hash(release, apiVersion, builder, expertApi, expertCommon, nanoSecure, swaggerUi);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Version {\n");
    sb.append("    release: ").append(toIndentedString(release)).append("\n");
    sb.append("    apiVersion: ").append(toIndentedString(apiVersion)).append("\n");
    sb.append("    builder: ").append(toIndentedString(builder)).append("\n");
    sb.append("    expertApi: ").append(toIndentedString(expertApi)).append("\n");
    sb.append("    expertCommon: ").append(toIndentedString(expertCommon)).append("\n");
    sb.append("    nanoSecure: ").append(toIndentedString(nanoSecure)).append("\n");
    sb.append("    swaggerUi: ").append(toIndentedString(swaggerUi)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("release");
    openapiFields.add("api-version");
    openapiFields.add("builder");
    openapiFields.add("expert-api");
    openapiFields.add("expert-common");
    openapiFields.add("nano-secure");
    openapiFields.add("swagger-ui");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("release");
    openapiRequiredFields.add("api-version");
    openapiRequiredFields.add("builder");
    openapiRequiredFields.add("expert-api");
    openapiRequiredFields.add("expert-common");
    openapiRequiredFields.add("nano-secure");
    openapiRequiredFields.add("swagger-ui");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to Version
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!Version.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Version is not found in the empty JSON string", Version.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!Version.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Version` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : Version.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("release").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `release` to be a primitive type in the JSON string but got `%s`", jsonObj.get("release").toString()));
      }
      if (!jsonObj.get("api-version").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `api-version` to be a primitive type in the JSON string but got `%s`", jsonObj.get("api-version").toString()));
      }
      if (!jsonObj.get("builder").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `builder` to be a primitive type in the JSON string but got `%s`", jsonObj.get("builder").toString()));
      }
      if (!jsonObj.get("expert-api").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `expert-api` to be a primitive type in the JSON string but got `%s`", jsonObj.get("expert-api").toString()));
      }
      if (!jsonObj.get("expert-common").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `expert-common` to be a primitive type in the JSON string but got `%s`", jsonObj.get("expert-common").toString()));
      }
      if (!jsonObj.get("nano-secure").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `nano-secure` to be a primitive type in the JSON string but got `%s`", jsonObj.get("nano-secure").toString()));
      }
      if (!jsonObj.get("swagger-ui").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `swagger-ui` to be a primitive type in the JSON string but got `%s`", jsonObj.get("swagger-ui").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Version.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Version' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Version> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Version.class));

       return (TypeAdapter<T>) new TypeAdapter<Version>() {
           @Override
           public void write(JsonWriter out, Version value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Version read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of Version given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of Version
  * @throws IOException if the JSON string is invalid with respect to Version
  */
  public static Version fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Version.class);
  }

 /**
  * Convert an instance of Version to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

